// PhotonEdge Blog Posts Data - Updated with new technical articles

var BLOG_POSTS = [
  {
    "id": 1,
    "title": "How to Choose the Right Optical Lens for Your Application",
    "slug": "choose-right-optical-lens",
    "url": "/blog.html",
    "excerpt": "A comprehensive guide to selecting optical lenses based on focal length, material, and coating requirements for different applications. Learn the key differences between plano convex, double concave, and achromatic lens types.",
    "category": "Technical Guide",
    "date": "2025-05-01",
    "readTime": "8 min",
    "image": "images/blog/choose-optical-lens.jpg",
    "author": "PhotonEdge Technical Team"
  },
  {
    "id": 2,
    "title": "Understanding Anti-Reflection Coatings: A Practical Guide",
    "slug": "anti-reflection-coatings-guide",
    "url": "/blog.html",
    "excerpt": "Everything you need to know about anti-reflection (AR) coatings for optical components. Discover how AR coatings work, the different types available, and how to choose the right coating for your wavelength and application.",
    "category": "Technical Guide",
    "date": "2025-04-28",
    "readTime": "7 min",
    "image": "images/blog/ar-coatings-guide.jpg",
    "author": "PhotonEdge Technical Team"
  },
  {
    "id": 3,
    "title": "BK7 vs UV Fused Silica: When to Use Which Material",
    "slug": "bk7-vs-uv-fused-silica",
    "url": "/blog.html",
    "excerpt": "A detailed comparison of BK7 and UV fused silica optical glass materials. Understand the differences in transmission range, thermal properties, and cost to make the right material choice for your optical system.",
    "category": "Technical Guide",
    "date": "2025-04-22",
    "readTime": "6 min",
    "image": "images/blog/bk7-vs-fused-silica.jpg",
    "author": "PhotonEdge Technical Team"
  },
  {
    "id": 4,
    "title": "5 Key Specifications to Check When Buying Optical Windows",
    "slug": "optical-windows-buying-guide",
    "url": "/blog.html",
    "excerpt": "Learn the five most critical specifications to evaluate when purchasing optical windows: surface flatness, parallelism, material transmission, clear aperture, and surface quality. Avoid costly mistakes with this buying guide.",
    "category": "Buying Guide",
    "date": "2025-04-15",
    "readTime": "6 min",
    "image": "images/blog/optical-windows-guide.jpg",
    "author": "PhotonEdge Sales Team"
  },
  {
    "id": 5,
    "title": "Optical Prism Types and Their Applications Explained",
    "slug": "optical-prism-types-applications",
    "url": "/blog.html",
    "excerpt": "An in-depth look at different optical prism types including right angle prisms, penta prisms, dove prisms, and corner cube prisms. Understand how each type works and where they are used in optical systems.",
    "category": "Technical Guide",
    "date": "2025-04-10",
    "readTime": "9 min",
    "image": "images/blog/prism-types.jpg",
    "author": "PhotonEdge Technical Team"
  },
  {
    "id": 6,
    "title": "Why PhotonEdge is Your Trusted Precision Optics Partner",
    "slug": "photonedge-trusted-optics-partner",
    "url": "/blog.html",
    "excerpt": "Discover why over 500 global clients trust PhotonEdge as their precision optics supplier. ISO 9001:2015 certified manufacturing, custom solutions, and fast delivery from our Beijing facility.",
    "category": "Company",
    "date": "2025-04-05",
    "readTime": "5 min",
    "image": "images/blog/photonedge-partner.jpg",
    "author": "PhotonEdge Team"
  },
  {
    "id": 7,
    "title": "Custom vs Stock Optics: When to Invest in Custom Optical Components",
    "slug": "custom-vs-stock-optics",
    "url": "/blog.html",
    "excerpt": "A practical guide comparing custom optical components with stock optics. Learn when standard parts are sufficient and when the investment in custom manufacturing delivers better long-term value for your optical system.",
    "category": "Buying Guide",
    "date": "2025-05-10",
    "readTime": "8 min",
    "image": "images/blog/custom-vs-stock-optics.jpg",
    "author": "PhotonEdge Technical Team"
  },
  {
    "id": 8,
    "title": "Laser Optics Selection Guide: Mirrors, Lenses, and Windows for High-Power Applications",
    "slug": "laser-optics-selection-guide",
    "url": "/blog.html",
    "excerpt": "Everything you need to know about selecting laser optics including high power laser mirrors, laser-grade lenses, and precision windows. Covers damage thresholds, coating types, and material selection for Nd:YAG, CO2, and fiber lasers.",
    "category": "Technical Guide",
    "date": "2025-05-10",
    "readTime": "10 min",
    "image": "images/blog/laser-optics-guide.jpg",
    "author": "PhotonEdge Technical Team"
  },
  {
    "id": 9,
    "title": "Optical Coating Types Explained: AR, HR, Beamsplitter, and Filter Coatings",
    "slug": "optical-coating-types-explained",
    "url": "/blog.html",
    "excerpt": "A comprehensive overview of optical coating types including anti-reflection coatings, high-reflectance HR coatings, beamsplitter coatings, and optical filter coatings. Understand how each coating type works and how to choose the right one for your application.",
    "category": "Technical Guide",
    "date": "2025-05-10",
    "readTime": "9 min",
    "image": "images/blog/optical-coatings.jpg",
    "author": "PhotonEdge Technical Team"
  },
  {
    "id": 10,
    "title": "How to Verify Optical Component Quality: Testing Methods and Standards",
    "slug": "optical-quality-testing-methods",
    "url": "/blog.html",
    "excerpt": "Learn about optical quality testing methods including interferometer testing for surface flatness, scratch-dig inspection for surface quality, LIDT testing, and international standards like MIL-PRF-13830B and ISO 10110.",
    "category": "Technical Guide",
    "date": "2025-05-10",
    "readTime": "9 min",
    "image": "images/blog/optical-quality-testing.jpg",
    "author": "PhotonEdge Quality Team"
  },
  {
    "id": 11,
    "title": "How to Specify Custom Optics: A Complete Engineering Guide",
    "slug": "custom-optics-specification-guide",
    "url": "/blog.html",
    "excerpt": "A comprehensive engineering guide to specifying custom optical components. Learn how to define material selection, surface quality, dimensional tolerances, coating requirements, and testing specifications to ensure your custom optics meet exact application needs.",
    "category": "Technical Guide",
    "date": "2025-05-15",
    "readTime": "12 min",
    "image": "images/blog/custom-optics-spec.jpg",
    "author": "PhotonEdge Engineering Team"
  },
  {
    "id": 12,
    "title": "Laser Damage Threshold: What Engineers Need to Know",
    "slug": "laser-damage-threshold-guide",
    "url": "/blog.html",
    "excerpt": "Understanding laser-induced damage threshold (LIDT) is critical for selecting optics in high-power laser applications. This guide covers LIDT testing standards,influencing factors, and practical specifications for CO2, Nd:YAG, and fiber lasers.",
    "category": "Technical Guide",
    "date": "2025-05-12",
    "readTime": "11 min",
    "image": "images/blog/laser-damage-threshold.jpg",
    "author": "PhotonEdge Technical Team"
  },
  {
    "id": 13,
    "title": "Optical Coating Design: From Theory to Practice",
    "slug": "optical-coating-design",
    "url": "/blog.html",
    "excerpt": "An in-depth exploration of optical coating design principles from thin-film theory to practical manufacturing. Learn about quarter-wave stacks, dielectric materials, coating processes, and how to specify coatings that meet your performance requirements.",
    "category": "Technical Guide",
    "date": "2025-05-08",
    "readTime": "14 min",
    "image": "images/blog/coating-design.jpg",
    "author": "PhotonEdge Engineering Team"
  },
  {
    "id": 14,
    "title": "Precision Optical Metrology: Interferometry and Beyond",
    "slug": "precision-optical-metrology",
    "url": "/blog.html",
    "excerpt": "A technical deep-dive into optical metrology techniques including Fizeau and Twyman-Green interferometry, profilometry, and wavefront sensing. Understand how measurement uncertainty affects optical component selection and quality assurance.",
    "category": "Technical Guide",
    "date": "2025-05-05",
    "readTime": "13 min",
    "image": "images/blog/optical-metrology.jpg",
    "author": "PhotonEdge Quality Team"
  },
  {
    "id": 15,
    "title": "Choosing Optical Materials for High-Power Laser Applications",
    "slug": "optical-materials-high-power-lasers",
    "url": "/blog.html",
    "excerpt": "A technical guide to selecting optical materials for high-power laser systems. Compare fused silica, BK7, CaF2, ZnSe, and diamond for different laser wavelengths, power levels, and environmental conditions.",
    "category": "Technical Guide",
    "date": "2025-05-02",
    "readTime": "11 min",
    "image": "images/blog/high-power-laser-materials.jpg",
    "author": "PhotonEdge Engineering Team"
  },
  {
    "id": 16,
    "title": "How to Choose a Precision Lenses Supplier: BK7 Plano-Convex vs Bi-Convex Guide",
    "slug": "precision-lenses-supplier-bk7-guide",
    "url": "/blog.html",
    "excerpt": "Comparing BK7 plano-convex and bi-convex lenses for optical system design. Learn when to choose each lens type, key specifications to verify with your precision lenses supplier, and how custom optics manufacturers like PhotonEdge ensure quality.",
    "category": "Technical Guide",
    "date": "2026-06-28",
    "readTime": "7 min",
    "image": "images/blog/choose-optical-lens.jpg",
    "author": "PhotonEdge Technical Team"
  },
  {
    "id": 17,
    "title": "Optical Components Manufacturer Guide: Mirrors, Prisms & Beamsplitters for Laser Systems",
    "slug": "optical-components-laser-systems-guide",
    "url": "/blog.html",
    "excerpt": "Complete guide to selecting optical components for laser systems from a trusted optical components manufacturer. Covers mirror coatings, prism types, beamsplitter specifications, and custom optics capabilities for industrial and research applications.",
    "category": "Technical Guide",
    "date": "2026-06-28",
    "readTime": "8 min",
    "image": "images/blog/laser-optics-guide.jpg",
    "author": "PhotonEdge Technical Team"
  },
  {
    "id": 18,
    "title": "UV Fused Silica vs BK7 Glass: Complete Material Selection Guide for Optical Engineers",
    "slug": "uv-fused-silica-vs-bk7-material-guide",
    "url": "/blog.html",
    "excerpt": "Detailed comparison of UV fused silica and BK7 optical glass for engineers. Covers transmission range, thermal properties, laser damage threshold, and cost considerations. Use our BK7 vs fused silica comparison to make the right material choice.",
    "category": "Technical Guide",
    "date": "2026-06-28",
    "readTime": "8 min",
    "image": "images/blog/bk7-vs-fused-silica.jpg",
    "author": "PhotonEdge Technical Team"
  },
  {
    "id": 19,
    "title": "Custom Optics Manufacturing: From Specification to Delivery at PhotonEdge",
    "slug": "custom-optics-manufacturing-process",
    "url": "/blog.html",
    "excerpt": "Inside look at the custom optics manufacturing process. Learn how precision optics manufacturers handle custom specifications, quality control, coating processes, and delivery timelines for OEM optical components and bespoke optical solutions.",
    "category": "Technical Guide",
    "date": "2026-06-28",
    "readTime": "6 min",
    "image": "images/blog/custom-optics-spec.jpg",
    "author": "PhotonEdge Technical Team"
  },
  {
    "id": 20,
    "title": "Anti-Reflection Coating Selection: AR Coatings for Visible, UV, and IR Applications",
    "slug": "anti-reflection-coating-selection-guide",
    "url": "/blog.html",
    "excerpt": "Comprehensive guide to anti-reflection coating selection across visible, UV, and IR wavelengths. Covers single-layer MgF2, broadband AR coatings, V-coat designs, laser damage threshold considerations, and how to specify AR coatings for your optical components.",
    "category": "Technical Guide",
    "date": "2026-06-28",
    "readTime": "7 min",
    "image": "images/blog/ar-coatings-guide.jpg",
    "author": "PhotonEdge Technical Team"
  }
];
