// PhotonEdge Blog Posts Data - Updated with Chinese translations

var BLOG_POSTS = [
  {
    "id": 1,
    "title": "How to Choose the Right Optical Lens for Your Application",
    "slug": "choose-right-optical-lens",
    "url": "/blog.html",
    "excerpt": "A comprehensive guide to selecting optical lenses based on focal length, material, and coating requirements for different applications. Learn the key differences between plano convex, double concave, and achromatic lens types.",
    "category": "Technical Guide",
    "date": "2025-05-01",
    "readTime": "8 min",
    "image": "images/blog/choose-optical-lens.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "如何为您的应用选择合适的光学透镜",
    "excerptZh": "全面指南：根据焦距、材料和镀膜要求为不同应用选择光学透镜。了解平凸透镜、双凹透镜和消色差透镜的关键区别。",
    "categoryZh": "技术指南"
  },
  {
    "id": 2,
    "title": "Understanding Anti-Reflection Coatings: A Practical Guide",
    "slug": "anti-reflection-coatings-guide",
    "url": "/blog.html",
    "excerpt": "Everything you need to know about anti-reflection (AR) coatings for optical components. Discover how AR coatings work, the different types available, and how to choose the right coating for your wavelength and application.",
    "category": "Technical Guide",
    "date": "2025-04-28",
    "readTime": "7 min",
    "image": "images/blog/ar-coatings-guide.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "理解减反射镀膜：实用指南",
    "excerptZh": "全面了解光学元件减反射（AR）镀膜。了解AR镀膜的工作原理、不同类型以及如何为波长和应用选择合适的镀膜。",
    "categoryZh": "技术指南"
  },
  {
    "id": 3,
    "title": "BK7 vs UV Fused Silica: When to Use Which Material",
    "slug": "bk7-vs-uv-fused-silica",
    "url": "/blog.html",
    "excerpt": "A detailed comparison of BK7 and UV fused silica optical glass materials. Understand the differences in transmission range, thermal properties, and cost to make the right material choice for your optical system.",
    "category": "Technical Guide",
    "date": "2025-04-22",
    "readTime": "6 min",
    "image": "images/blog/bk7-vs-fused-silica.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "BK7与紫外熔融石英：何时使用哪种材料",
    "excerptZh": "BK7和紫外熔融石英光学玻璃材料的详细对比。了解透过范围、热性能和成本的差异，为您的光学系统做出正确的材料选择。",
    "categoryZh": "技术指南"
  },
  {
    "id": 4,
    "title": "5 Key Specifications to Check When Buying Optical Windows",
    "slug": "optical-windows-buying-guide",
    "url": "/blog.html",
    "excerpt": "Learn the five most critical specifications to evaluate when purchasing optical windows: surface flatness, parallelism, material transmission, clear aperture, and surface quality. Avoid costly mistakes with this buying guide.",
    "category": "Buying Guide",
    "date": "2025-04-15",
    "readTime": "6 min",
    "image": "images/blog/optical-windows-guide.jpg",
    "author": "PhotonEdge Sales Team",
    "titleZh": "购买光学窗口时需检查的5个关键规格",
    "excerptZh": "购买光学窗口时需评估的五个最关键规格：表面平整度、平行度、材料透过率、通光孔径和表面质量。避免代价高昂的错误。",
    "categoryZh": "购买指南"
  },
  {
    "id": 5,
    "title": "Optical Prism Types and Their Applications Explained",
    "slug": "optical-prism-types-applications",
    "url": "/blog.html",
    "excerpt": "An in-depth look at different optical prism types including right angle prisms, penta prisms, dove prisms, and corner cube prisms. Understand how each type works and where they are used in optical systems.",
    "category": "Technical Guide",
    "date": "2025-04-10",
    "readTime": "9 min",
    "image": "images/blog/prism-types.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "光学棱镜类型及其应用详解",
    "excerptZh": "深入介绍不同类型的光学棱镜，包括直角棱镜、五棱镜、道威棱镜和角锥棱镜。了解每种类型的工作原理及其在光学系统中的应用。",
    "categoryZh": "技术指南"
  },
  {
    "id": 6,
    "title": "Why PhotonEdge is Your Trusted Precision Optics Partner",
    "slug": "photonedge-trusted-optics-partner",
    "url": "/blog.html",
    "excerpt": "Discover why over 500 global clients trust PhotonEdge as their precision optics supplier. ISO 9001:2015 certified manufacturing, custom solutions, and fast delivery from our Beijing facility.",
    "category": "Company",
    "date": "2025-04-05",
    "readTime": "5 min",
    "image": "images/blog/photonedge-partner.jpg",
    "author": "PhotonEdge Team",
    "titleZh": "为什么选择恒鼎光作为您值得信赖的精密光学合作伙伴",
    "excerptZh": "了解为何超过500家全球客户信赖恒鼎光作为精密光学供应商。ISO 9001:2015认证制造、定制解决方案，北京工厂快速交付。",
    "categoryZh": "公司动态"
  },
  {
    "id": 7,
    "title": "Custom vs Stock Optics: When to Invest in Custom Optical Components",
    "slug": "custom-vs-stock-optics",
    "url": "/blog.html",
    "excerpt": "A practical guide comparing custom optical components with stock optics. Learn when standard parts are sufficient and when the investment in custom manufacturing delivers better long-term value for your optical system.",
    "category": "Buying Guide",
    "date": "2025-05-10",
    "readTime": "8 min",
    "image": "images/blog/custom-vs-stock-optics.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "定制光学 vs 标准光学：何时投资定制光学元件",
    "excerptZh": "实用指南：比较定制光学元件与标准光学的差异。了解标准件何时足够，何时定制制造能为光学系统带来更好的长期价值。",
    "categoryZh": "购买指南"
  },
  {
    "id": 8,
    "title": "Laser Optics Selection Guide: Mirrors, Lenses, and Windows for High-Power Applications",
    "slug": "laser-optics-selection-guide",
    "url": "/blog.html",
    "excerpt": "Everything you need to know about selecting laser optics including high power laser mirrors, laser-grade lenses, and precision windows. Covers damage thresholds, coating types, and material selection for Nd:YAG, CO2, and fiber lasers.",
    "category": "Technical Guide",
    "date": "2025-05-10",
    "readTime": "10 min",
    "image": "images/blog/laser-optics-guide.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "激光光学选型指南：高功率应用的反射镜、透镜和窗口",
    "excerptZh": "激光光学选型全攻略，包括高功率激光反射镜、激光级透镜和精密窗口。涵盖损伤阈值、镀膜类型以及Nd:YAG、CO2和光纤激光的材料选择。",
    "categoryZh": "技术指南"
  },
  {
    "id": 9,
    "title": "Optical Coating Types Explained: AR, HR, Beamsplitter, and Filter Coatings",
    "slug": "optical-coating-types-explained",
    "url": "/blog.html",
    "excerpt": "A comprehensive overview of optical coating types including anti-reflection coatings, high-reflectance HR coatings, beamsplitter coatings, and optical filter coatings. Understand how each coating type works and how to choose the right one for your application.",
    "category": "Technical Guide",
    "date": "2025-05-10",
    "readTime": "9 min",
    "image": "images/blog/optical-coatings.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "光学镀膜类型详解：AR、HR、分光片和滤光片镀膜",
    "excerptZh": "光学镀膜类型全面概述，包括减反射镀膜、高反射HR镀膜、分光镀膜和光学滤光片镀膜。了解每种镀膜的工作原理及如何为应用选择合适的镀膜。",
    "categoryZh": "技术指南"
  },
  {
    "id": 10,
    "title": "How to Verify Optical Component Quality: Testing Methods and Standards",
    "slug": "optical-quality-testing-methods",
    "url": "/blog.html",
    "excerpt": "Learn about optical quality testing methods including interferometer testing for surface flatness, scratch-dig inspection for surface quality, LIDT testing, and international standards like MIL-PRF-13830B and ISO 10110.",
    "category": "Technical Guide",
    "date": "2025-05-10",
    "readTime": "9 min",
    "image": "images/blog/optical-quality-testing.jpg",
    "author": "PhotonEdge Quality Team",
    "titleZh": "如何验证光学元件质量：测试方法与标准",
    "excerptZh": "了解光学质量测试方法，包括干涉仪表面平整度检测、划痕-麻点表面质量检查、LIDT测试以及MIL-PRF-13830B和ISO 10110等国际标准。",
    "categoryZh": "技术指南"
  },
  {
    "id": 11,
    "title": "How to Specify Custom Optics: A Complete Engineering Guide",
    "slug": "custom-optics-specification-guide",
    "url": "/blog.html",
    "excerpt": "A comprehensive engineering guide to specifying custom optical components. Learn how to define material selection, surface quality, dimensional tolerances, coating requirements, and testing specifications to ensure your custom optics meet exact application needs.",
    "category": "Technical Guide",
    "date": "2025-05-15",
    "readTime": "12 min",
    "image": "images/blog/custom-optics-spec.jpg",
    "author": "PhotonEdge Engineering Team",
    "titleZh": "如何制定定制光学规格：完整工程指南",
    "excerptZh": "定制光学元件规格制定的完整工程指南。学习如何定义材料选择、表面质量、尺寸公差、镀膜要求和测试规格，确保定制光学满足应用需求。",
    "categoryZh": "技术指南"
  },
  {
    "id": 12,
    "title": "Laser Damage Threshold: What Engineers Need to Know",
    "slug": "laser-damage-threshold-guide",
    "url": "/blog.html",
    "excerpt": "Understanding laser-induced damage threshold (LIDT) is critical for selecting optics in high-power laser applications. This guide covers LIDT testing standards,influencing factors, and practical specifications for CO2, Nd:YAG, and fiber lasers.",
    "category": "Technical Guide",
    "date": "2025-05-12",
    "readTime": "11 min",
    "image": "images/blog/laser-damage-threshold.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "激光损伤阈值：工程师必知指南",
    "excerptZh": "了解激光损伤阈值（LIDT）对高功率激光应用中光学元件选型至关重要。本指南涵盖LIDT测试标准、影响因素以及CO2、Nd:YAG和光纤激光的实用规格。",
    "categoryZh": "技术指南"
  },
  {
    "id": 13,
    "title": "Optical Coating Design: From Theory to Practice",
    "slug": "optical-coating-design",
    "url": "/blog.html",
    "excerpt": "An in-depth exploration of optical coating design principles from thin-film theory to practical manufacturing. Learn about quarter-wave stacks, dielectric materials, coating processes, and how to specify coatings that meet your performance requirements.",
    "category": "Technical Guide",
    "date": "2025-05-08",
    "readTime": "14 min",
    "image": "images/blog/coating-design.jpg",
    "author": "PhotonEdge Engineering Team",
    "titleZh": "光学镀膜设计：从理论到实践",
    "excerptZh": "深入探讨光学镀膜设计原理，从薄膜理论到实际制造。了解四分之一波长堆栈、介电材料、镀膜工艺以及如何指定满足性能要求的镀膜。",
    "categoryZh": "技术指南"
  },
  {
    "id": 14,
    "title": "Precision Optical Metrology: Interferometry and Beyond",
    "slug": "precision-optical-metrology",
    "url": "/blog.html",
    "excerpt": "A technical deep-dive into optical metrology techniques including Fizeau and Twyman-Green interferometry, profilometry, and wavefront sensing. Understand how measurement uncertainty affects optical component selection and quality assurance.",
    "category": "Technical Guide",
    "date": "2025-05-05",
    "readTime": "13 min",
    "image": "images/blog/optical-metrology.jpg",
    "author": "PhotonEdge Quality Team",
    "titleZh": "精密光学计量学：干涉测量及其他",
    "excerptZh": "光学计量技术深度解析，包括Fizeau和Twyman-Green干涉测量、轮廓测量和波前传感。了解测量不确定度如何影响光学元件选型和质量保证。",
    "categoryZh": "技术指南"
  },
  {
    "id": 15,
    "title": "Choosing Optical Materials for High-Power Laser Applications",
    "slug": "optical-materials-high-power-lasers",
    "url": "/blog.html",
    "excerpt": "A technical guide to selecting optical materials for high-power laser systems. Compare fused silica, BK7, CaF2, ZnSe, and diamond for different laser wavelengths, power levels, and environmental conditions.",
    "category": "Technical Guide",
    "date": "2025-05-02",
    "readTime": "11 min",
    "image": "images/blog/high-power-laser-materials.jpg",
    "author": "PhotonEdge Engineering Team",
    "titleZh": "高功率激光应用中的光学材料选择",
    "excerptZh": "高功率激光系统光学材料选择技术指南。比较熔融石英、BK7、CaF2、ZnSe和金刚石在不同激光波长、功率水平和环境条件下的应用。",
    "categoryZh": "技术指南"
  },
  {
    "id": 16,
    "title": "How to Choose a Precision Lenses Supplier: BK7 Plano-Convex vs Bi-Convex Guide",
    "slug": "precision-lenses-supplier-bk7-guide",
    "url": "/blog.html",
    "excerpt": "Comparing BK7 plano-convex and bi-convex lenses for optical system design. Learn when to choose each lens type, key specifications to verify with your precision lenses supplier, and how custom optics manufacturers like PhotonEdge ensure quality.",
    "category": "Technical Guide",
    "date": "2026-06-28",
    "readTime": "7 min",
    "image": "images/blog/choose-optical-lens.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "如何选择精密透镜供应商：BK7平凸与双凸透镜指南",
    "excerptZh": "光学系统设计中BK7平凸和双凸透镜的对比。了解每种透镜类型的适用场景、向精密透镜供应商验证的关键规格，以及恒鼎光等定制光学制造商如何保证质量。",
    "categoryZh": "技术指南"
  },
  {
    "id": 17,
    "title": "Optical Components Manufacturer Guide: Mirrors, Prisms & Beamsplitters for Laser Systems",
    "slug": "optical-components-laser-systems-guide",
    "url": "/blog.html",
    "excerpt": "Complete guide to selecting optical components for laser systems from a trusted optical components manufacturer. Covers mirror coatings, prism types, beamsplitter specifications, and custom optics capabilities for industrial and research applications.",
    "category": "Technical Guide",
    "date": "2026-06-28",
    "readTime": "8 min",
    "image": "images/blog/laser-optics-guide.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "光学元件制造商指南：激光系统的反射镜、棱镜和分光片",
    "excerptZh": "来自可靠光学元件制造商的激光系统光学元件选型完整指南。涵盖反射镜镀膜、棱镜类型、分光片规格以及工业和研究应用的定制光学能力。",
    "categoryZh": "技术指南"
  },
  {
    "id": 18,
    "title": "UV Fused Silica vs BK7 Glass: Complete Material Selection Guide for Optical Engineers",
    "slug": "uv-fused-silica-vs-bk7-material-guide",
    "url": "/blog.html",
    "excerpt": "Detailed comparison of UV fused silica and BK7 optical glass for engineers. Covers transmission range, thermal properties, laser damage threshold, and cost considerations. Use our BK7 vs fused silica comparison to make the right material choice.",
    "category": "Technical Guide",
    "date": "2026-06-28",
    "readTime": "8 min",
    "image": "images/blog/bk7-vs-fused-silica.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "紫外熔融石英 vs BK7玻璃：光学工程师的完整材料选择指南",
    "excerptZh": "面向工程师的紫外熔融石英和BK7光学玻璃详细对比。涵盖透过范围、热性能、激光损伤阈值和成本考量。使用BK7与熔融石英对比做出正确材料选择。",
    "categoryZh": "技术指南"
  },
  {
    "id": 19,
    "title": "Custom Optics Manufacturing: From Specification to Delivery at PhotonEdge",
    "slug": "custom-optics-manufacturing-process",
    "url": "/blog.html",
    "excerpt": "Inside look at the custom optics manufacturing process. Learn how precision optics manufacturers handle custom specifications, quality control, coating processes, and delivery timelines for OEM optical components and bespoke optical solutions.",
    "category": "Technical Guide",
    "date": "2026-06-28",
    "readTime": "6 min",
    "image": "images/blog/custom-optics-spec.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "定制光学制造：从规格到交付——恒鼎光全流程解析",
    "excerptZh": "定制光学制造流程深度解析。了解精密光学制造商如何处理定制规格、质量控制、镀膜工艺和交付周期，提供OEM光学元件和定制光学解决方案。",
    "categoryZh": "技术指南"
  },
  {
    "id": 20,
    "title": "Anti-Reflection Coating Selection: AR Coatings for Visible, UV, and IR Applications",
    "slug": "anti-reflection-coating-selection-guide",
    "url": "/blog.html",
    "excerpt": "Comprehensive guide to anti-reflection coating selection across visible, UV, and IR wavelengths. Covers single-layer MgF2, broadband AR coatings, V-coat designs, laser damage threshold considerations, and how to specify AR coatings for your optical components.",
    "category": "Technical Guide",
    "date": "2026-06-28",
    "readTime": "7 min",
    "image": "images/blog/ar-coatings-guide.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "减反射镀膜选型：可见光、紫外和红外应用的AR镀膜",
    "excerptZh": "可见光、紫外和红外波段的减反射镀膜选型全面指南。涵盖单层MgF2、宽带AR镀膜、V涂层设计、激光损伤阈值考量以及如何为光学元件指定AR镀膜。",
    "categoryZh": "技术指南"
  }
];
