// PhotonEdge Blog Posts Data - Updated with new technical articles

var BLOG_POSTS = [
  {
    "id": 1,
    "title": "How to Choose the Right Optical Lens for Your Application",
    "slug": "choose-right-optical-lens",
    "url": "/blog/choose-right-optical-lens/",
    "excerpt": "A comprehensive guide to selecting optical lenses based on focal length, material, and coating requirements for different applications. Learn the key differences between plano convex, double concave, and achromatic lens types.",
    "category": "Technical Guide",
    "date": "2025-05-01",
    "readTime": "8 min",
    "image": "images/blog/choose-optical-lens.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "如何为您的应用选择合适的光学透镜",
    "excerptZh": "根据焦距、材料和镀膜要求选择光学透镜的全面指南。了解平凸、双凹和消色差透镜类型的关键差异。",
    "categoryZh": "技术指南"
  },
  {
    "id": 2,
    "title": "Understanding Anti-Reflection Coatings: A Practical Guide",
    "slug": "anti-reflection-coatings-guide",
    "url": "/blog/anti-reflection-coatings-guide/",
    "excerpt": "Everything you need to know about anti-reflection (AR) coatings for optical components. Discover how AR coatings work, the different types available, and how to choose the right coating for your wavelength and application.",
    "category": "Technical Guide",
    "date": "2025-04-28",
    "readTime": "7 min",
    "image": "images/blog/ar-coatings-guide.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "增透膜实用指南",
    "excerptZh": "关于光学元件增透膜(AR)您需要了解的一切。了解AR膜的工作原理、类型以及如何选择适合您波长和应用的镀膜。",
    "categoryZh": "技术指南"
  },
  {
    "id": 3,
    "title": "BK7 vs UV Fused Silica: When to Use Which Material",
    "slug": "bk7-vs-uv-fused-silica",
    "url": "/blog/bk7-vs-uv-fused-silica/",
    "excerpt": "A detailed comparison of BK7 and UV fused silica optical glass materials. Understand the differences in transmission range, thermal properties, and cost to make the right material choice for your optical system.",
    "category": "Technical Guide",
    "date": "2025-04-22",
    "readTime": "6 min",
    "image": "images/blog/bk7-vs-fused-silica.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "BK7与紫外熔石英：何时使用哪种材料",
    "excerptZh": "BK7和紫外熔石英光学玻璃材料的详细对比。了解透过率范围、热性能和成本差异，做出正确的材料选择。",
    "categoryZh": "技术指南"
  },
  {
    "id": 4,
    "title": "5 Key Specifications to Check When Buying Optical Windows",
    "slug": "optical-windows-buying-guide",
    "url": "/blog/optical-windows-buying-guide/",
    "excerpt": "Learn the five most critical specifications to evaluate when purchasing optical windows: surface flatness, parallelism, material transmission, clear aperture, and surface quality. Avoid costly mistakes with this buying guide.",
    "category": "Buying Guide",
    "date": "2025-04-15",
    "readTime": "6 min",
    "image": "images/blog/optical-windows-guide.jpg",
    "author": "PhotonEdge Sales Team",
    "titleZh": "购买光学窗口片需检查的5个关键规格",
    "excerptZh": "选择光学窗口片时必须关注的5个关键规格参数。从材料、面形精度到镀膜，确保采购无忧。",
    "categoryZh": "购买指南"
  },
  {
    "id": 5,
    "title": "Optical Prism Types and Their Applications Explained",
    "slug": "optical-prism-types-applications",
    "url": "/blog/optical-prism-types-applications/",
    "excerpt": "An in-depth look at different optical prism types including right angle prisms, penta prisms, dove prisms, and corner cube prisms. Understand how each type works and where they are used in optical systems.",
    "category": "Technical Guide",
    "date": "2025-04-10",
    "readTime": "9 min",
    "image": "images/blog/prism-types.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "光学棱镜类型及其应用详解",
    "excerptZh": "直角棱镜、五角棱镜、角锥棱镜等各类型棱镜的工作原理和应用场景详解。",
    "categoryZh": "技术指南"
  },
  {
    "id": 6,
    "title": "Why PhotonEdge is Your Trusted Precision Optics Partner",
    "slug": "photonedge-trusted-optics-partner",
    "url": "/blog/photonedge-trusted-optics-partner/",
    "excerpt": "Discover why over 500 global clients trust PhotonEdge as their precision optics supplier. ISO 9001:2015 certified manufacturing, custom solutions, and fast delivery from our Beijing facility.",
    "category": "Company",
    "date": "2025-04-05",
    "readTime": "5 min",
    "image": "images/blog/photonedge-partner.jpg",
    "author": "PhotonEdge Team",
    "titleZh": "为什么恒鼎光是您值得信赖的精密光学合作伙伴",
    "excerptZh": "了解恒鼎光如何以15年+行业经验和全体系质量保证，为全球客户提供优质光学元件。",
    "categoryZh": "公司动态"
  },
  {
    "id": 7,
    "title": "Custom vs Stock Optics: When to Invest in Custom Optical Components",
    "slug": "custom-vs-stock-optics",
    "url": "/blog/custom-vs-stock-optics/",
    "excerpt": "A practical guide comparing custom optical components with stock optics. Learn when standard parts are sufficient and when the investment in custom manufacturing delivers better long-term value for your optical system.",
    "category": "Buying Guide",
    "date": "2025-05-10",
    "readTime": "8 min",
    "image": "images/blog/custom-vs-stock-optics.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "定制与标准光学元件：何时投资定制",
    "excerptZh": "标准库存产品和定制加工的优缺点对比，帮助您做出最佳采购决策。",
    "categoryZh": "购买指南"
  },
  {
    "id": 8,
    "title": "Laser Optics Selection Guide: Mirrors, Lenses, and Windows for High-Power Applications",
    "slug": "laser-optics-selection-guide",
    "url": "/blog/laser-optics-selection-guide/",
    "excerpt": "Everything you need to know about selecting laser optics including high power laser mirrors, laser-grade lenses, and precision windows. Covers damage thresholds, coating types, and material selection for Nd:YAG, CO2, and fiber lasers.",
    "category": "Technical Guide",
    "date": "2025-05-10",
    "readTime": "10 min",
    "image": "images/blog/laser-optics-guide.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "激光光学元件选型指南",
    "excerptZh": "涵盖反射镜、透镜和窗口片的激光光学元件选型要点，包括损伤阈值和镀膜选择。",
    "categoryZh": "技术指南"
  },
  {
    "id": 9,
    "title": "Optical Coating Types Explained: AR, HR, Beamsplitter, and Filter Coatings",
    "slug": "optical-coating-types-explained",
    "url": "/blog/optical-coating-types-explained/",
    "excerpt": "A comprehensive overview of optical coating types including anti-reflection coatings, high-reflectance HR coatings, beamsplitter coatings, and optical filter coatings. Understand how each coating type works and how to choose the right one for your application.",
    "category": "Technical Guide",
    "date": "2025-05-10",
    "readTime": "9 min",
    "image": "images/blog/optical-coatings.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "光学镀膜类型详解",
    "excerptZh": "增透膜、高反膜、分光膜和滤光膜的原理、类型和应用场景全面介绍。",
    "categoryZh": "技术指南"
  },
  {
    "id": 10,
    "title": "How to Verify Optical Component Quality: Testing Methods and Standards",
    "slug": "optical-quality-testing-methods",
    "url": "/blog/optical-quality-testing-methods/",
    "excerpt": "Learn about optical quality testing methods including interferometer testing for surface flatness, scratch-dig inspection for surface quality, LIDT testing, and international standards like MIL-PRF-13830B and ISO 10110.",
    "category": "Technical Guide",
    "date": "2025-05-10",
    "readTime": "9 min",
    "image": "images/blog/optical-quality-testing.jpg",
    "author": "PhotonEdge Quality Team",
    "titleZh": "如何验证光学元件质量：检测方法",
    "excerptZh": "干涉测量、表面质量检查、尺寸测量和镀膜检测等光学元件质量检测方法详解。",
    "categoryZh": "技术指南"
  },
  {
    "id": 11,
    "title": "How to Specify Custom Optics: A Complete Engineering Guide",
    "slug": "custom-optics-specification-guide",
    "url": "/blog/custom-optics-specification-guide/",
    "excerpt": "A comprehensive engineering guide to specifying custom optical components. Learn how to define material selection, surface quality, dimensional tolerances, coating requirements, and testing specifications to ensure your custom optics meet exact application needs.",
    "category": "Technical Guide",
    "date": "2025-05-15",
    "readTime": "12 min",
    "image": "images/blog/custom-optics-spec.jpg",
    "author": "PhotonEdge Engineering Team",
    "titleZh": "如何编写定制光学元件规格书",
    "excerptZh": "从基本规格到光学参数、镀膜要求，完整的光学元件规格书编写指导。",
    "categoryZh": "技术指南"
  },
  {
    "id": 12,
    "title": "Laser Damage Threshold: What Engineers Need to Know",
    "slug": "laser-damage-threshold-guide",
    "url": "/blog/laser-damage-threshold-guide/",
    "excerpt": "Understanding laser-induced damage threshold (LIDT) is critical for selecting optics in high-power laser applications. This guide covers LIDT testing standards,influencing factors, and practical specifications for CO2, Nd:YAG, and fiber lasers.",
    "category": "Technical Guide",
    "date": "2025-05-12",
    "readTime": "11 min",
    "image": "images/blog/laser-damage-threshold.jpg",
    "author": "PhotonEdge Technical Team",
    "titleZh": "激光损伤阈值：工程师需知",
    "excerptZh": "理解和使用LIDT数据的关键指南，帮助工程师选择合适的激光光学元件。",
    "categoryZh": "技术指南"
  },
  {
    "id": 13,
    "title": "Optical Coating Design: From Theory to Practice",
    "slug": "optical-coating-design",
    "url": "/blog/optical-coating-design/",
    "excerpt": "An in-depth exploration of optical coating design principles from thin-film theory to practical manufacturing. Learn about quarter-wave stacks, dielectric materials, coating processes, and how to specify coatings that meet your performance requirements.",
    "category": "Technical Guide",
    "date": "2025-05-08",
    "readTime": "14 min",
    "image": "images/blog/coating-design.jpg",
    "author": "PhotonEdge Engineering Team",
    "titleZh": "光学镀膜设计：从理论到实践",
    "excerptZh": "薄膜干涉原理、设计方法、材料选择和实践经验的全面介绍。",
    "categoryZh": "技术指南"
  },
  {
    "id": 14,
    "title": "Precision Optical Metrology: Interferometry and Beyond",
    "slug": "precision-optical-metrology",
    "url": "/blog/precision-optical-metrology/",
    "excerpt": "A technical deep-dive into optical metrology techniques including Fizeau and Twyman-Green interferometry, profilometry, and wavefront sensing. Understand how measurement uncertainty affects optical component selection and quality assurance.",
    "category": "Technical Guide",
    "date": "2025-05-05",
    "readTime": "13 min",
    "image": "images/blog/optical-metrology.jpg",
    "author": "PhotonEdge Quality Team",
    "titleZh": "精密光学计量：干涉测量与波前检测",
    "excerptZh": "Fizeau干涉仪、波前传感器和表面粗糙度测量等先进光学计量技术介绍。",
    "categoryZh": "技术指南"
  },
  {
    "id": 15,
    "title": "Choosing Optical Materials for High-Power Laser Applications",
    "slug": "optical-materials-high-power-lasers",
    "url": "/blog/optical-materials-high-power-lasers/",
    "excerpt": "A technical guide to selecting optical materials for high-power laser systems. Compare fused silica, BK7, CaF2, ZnSe, and diamond for different laser wavelengths, power levels, and environmental conditions.",
    "category": "Technical Guide",
    "date": "2025-05-02",
    "readTime": "11 min",
    "image": "images/blog/high-power-laser-materials.jpg",
    "author": "PhotonEdge Engineering Team",
    "titleZh": "高功率激光应用的光学材料选择",
    "excerptZh": "为高功率激光系统选择合适材料的指导，包括LIDT对比和热性能分析。",
    "categoryZh": "技术指南"
  }
];
