#!/usr/bin/env python3
# Build new products-data.js based on catalog

products = [
    # ===== 光学透镜 Optical Lenses =====
    {
        "id": 1,
        "name": "BK7 Plano-Convex Lenses",
        "nameZh": "BK7平凸透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "BK7 plano-convex lenses feature a positive focal length, widely used for focusing and collimating light beams. Available with AR coatings for 350-650nm, 650-950nm, or 950-1250nm wavelength ranges.",
        "descriptionZh": "BK7平凸透镜具有正焦距，被广泛用于光束的聚焦和准直。可提供350-650nm、650-950nm、950-1250nm波段增透膜。",
        "image": "images/products/optical-lenses/bk7-plano-convex-lenses.jpg",
        "parameters": {
            "material": "K9 (BK7)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "A: AR 350-650nm / B: AR 650-950nm / C: AR 950-1250nm"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "bk7-plano-convex-lenses"
    },
    {
        "id": 2,
        "name": "BK7 Bi-Convex Lenses",
        "nameZh": "BK7双凸透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "BK7 bi-convex lenses feature a positive focal length, primarily used for light collimation and focusing. Both surfaces are convex, providing symmetrical light bending.",
        "descriptionZh": "BK7双凸透镜具有正焦距，主要用于光的准直和聚焦。两面均为凸面，提供对称的光线折射。",
        "image": "images/products/optical-lenses/bk7-bi-convex-lenses.jpg",
        "parameters": {
            "material": "H-K9L (BK7)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "A: AR 350-650nm / B: AR 650-950nm / C: AR 950-1250nm"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "bk7-bi-convex-lenses"
    },
    {
        "id": 3,
        "name": "BK7 Plano-Concave Lenses",
        "nameZh": "BK7平凹透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "BK7 plano-concave lenses have a negative focal length. Parallel beams passing through become divergent. Uniform material with no streaks, impurities, or bubbles.",
        "descriptionZh": "BK7平凹透镜的焦距为负，平行光束通过后呈发散状。均匀性好，无纹理、杂质、气泡。",
        "image": "images/products/optical-lenses/bk7-plano-concave-lenses.jpg",
        "parameters": {
            "material": "H-K9L (BK7)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "A: AR 350-650nm / B: AR 650-950nm / C: AR 950-1250nm"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "bk7-plano-concave-lenses"
    },
    {
        "id": 4,
        "name": "BK7 Bi-Concave Lenses",
        "nameZh": "BK7双凹透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "BK7 bi-concave lenses feature a negative focal length, mainly used for diverging parallel light and forming virtual images. Available in multiple specifications.",
        "descriptionZh": "BK7双凹透镜具有负焦距，主要用于发散平行光并形成虚像。可提供多种规格。",
        "image": "images/products/optical-lenses/bk7-bi-concave-lenses.jpg",
        "parameters": {
            "material": "H-K9L (BK7)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "A: AR 350-650nm / B: AR 650-950nm / C: AR 950-1250nm"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "bk7-bi-concave-lenses"
    },
    {
        "id": 5,
        "name": "BK7 Positive Meniscus Lenses",
        "nameZh": "BK7正弯月透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "BK7 positive meniscus lenses are convex-concave lenses thicker at the center. Used to reduce spherical aberration and, when combined with other lenses, can reduce system focal length and increase numerical aperture.",
        "descriptionZh": "BK7正弯月透镜是一种中间比边缘厚的凸凹透镜，可减小球差。与其他透镜组合时可减小系统焦距并扩大数值孔径。",
        "image": "images/products/optical-lenses/bk7-positive-meniscus-lenses.jpg",
        "parameters": {
            "material": "K9 (BK7)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "A: AR 350-650nm / B: AR 650-950nm / C: AR 950-1250nm"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "bk7-positive-meniscus-lenses"
    },
    {
        "id": 6,
        "name": "BK7 Negative Meniscus Lenses",
        "nameZh": "BK7负弯月透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "BK7 negative meniscus lenses are convex-concave lenses thinner at the center. They can reduce spherical aberration and, when combined with other lenses, decrease the numerical aperture of the system.",
        "descriptionZh": "BK7负弯月透镜是一种中间比边缘薄的凸凹透镜，可减小球差。与其他透镜组合可降低系统的数值孔径。",
        "image": "images/products/optical-lenses/bk7-negative-meniscus-lenses.jpg",
        "parameters": {
            "material": "H-K9L (BK7)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "A: AR 350-650nm / B: AR 650-950nm / C: AR 950-1250nm"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "bk7-negative-meniscus-lenses"
    },
    {
        "id": 7,
        "name": "UV Fused Silica Plano-Convex Lenses",
        "nameZh": "UV熔融石英平凸透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "UV fused silica plano-convex lenses offer high transmittance in the 195nm-2100nm wavelength range, making them ideal for UV applications. Custom coatings available.",
        "descriptionZh": "UV熔融石英平凸透镜在195nm-2100nm波段有较高透过率，是紫外波段应用的理想选择。可定制镀膜。",
        "image": "images/products/optical-lenses/uv-fused-silica-plano-convex-lenses.jpg",
        "parameters": {
            "material": "UV Fused Silica (JGS1)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "Custom Design"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "uv-fused-silica-plano-convex-lenses"
    },
    {
        "id": 8,
        "name": "UV Fused Silica Bi-Convex Lenses",
        "nameZh": "UV熔融石英双凸透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "UV fused silica bi-convex lenses provide high transmittance in the 195-2100nm range. Compared to BK7, this material offers superior UV transmission. Custom coatings available.",
        "descriptionZh": "UV熔融石英双凸透镜在195-2100nm波段有较高透过率，相比BK7材料在紫外波段有更高透过率。可定制镀膜。",
        "image": "images/products/optical-lenses/uv-fused-silica-bi-convex-lenses.jpg",
        "parameters": {
            "material": "UV Fused Silica (JGS1)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "Custom Design"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "uv-fused-silica-bi-convex-lenses"
    },
    {
        "id": 9,
        "name": "UV Fused Silica Plano-Concave Lenses",
        "nameZh": "UV熔融石英平凹透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "UV fused silica plano-concave lenses feature a negative focal length with high transmittance in the 195-2100nm range. Multiple sizes available with custom design coatings.",
        "descriptionZh": "UV熔融石英平凹透镜具有负焦距，在195-2100nm波段有较高透过率。可提供多种尺寸规格，可定制镀膜。",
        "image": "images/products/optical-lenses/uv-fused-silica-plano-concave-lenses.jpg",
        "parameters": {
            "material": "UV Fused Silica (JGS1)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "Custom Design"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "uv-fused-silica-plano-concave-lenses"
    },
    {
        "id": 10,
        "name": "UV Fused Silica Bi-Concave Lenses",
        "nameZh": "UV熔融石英双凹透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "UV fused silica bi-concave lenses feature a negative focal length with high UV to NIR transmittance (195-2100nm). Multiple specifications available with custom coatings.",
        "descriptionZh": "UV熔融石英双凹透镜具有负焦距，在195-2100nm波段有较高透过率。可提供多种规格，可定制镀膜。",
        "image": "images/products/optical-lenses/uv-fused-silica-bi-concave-lenses.jpg",
        "parameters": {
            "material": "UV Fused Silica (JGS1)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "Custom Design"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "uv-fused-silica-bi-concave-lenses"
    },
    {
        "id": 11,
        "name": "BK7 Plano-Convex Cylindrical Lenses",
        "nameZh": "BK7平凸柱面透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "BK7 plano-convex cylindrical lenses are used for linear imaging and single-axis magnification. Ideal for laser convergence or forming sheet-like beams.",
        "descriptionZh": "BK7平凸柱面透镜主要用于线性成像及宽范围内单轴放大，可用于激光汇聚或汇聚成片状光束。",
        "image": "images/products/optical-lenses/bk7-plano-convex-cylindrical-lenses.jpg",
        "parameters": {
            "material": "H-K9L (BK7)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "A: AR 350-650nm / B: AR 650-950nm / C: AR 950-1250nm"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "bk7-plano-convex-cylindrical-lenses"
    },
    {
        "id": 12,
        "name": "BK7 Plano-Concave Cylindrical Lenses",
        "nameZh": "BK7平凹柱面透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "BK7 plano-concave cylindrical lenses have a negative effective focal length, diverging light in one dimension. Can be combined with plano-convex cylindrical lenses for beam expansion.",
        "descriptionZh": "BK7平凹柱面透镜的有效焦距为负，可将光发散到一个维度，可与平凸柱面透镜组合用于光束扩束。",
        "image": "images/products/optical-lenses/bk7-plano-concave-cylindrical-lenses.jpg",
        "parameters": {
            "material": "H-K9L (BK7)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "A: AR 350-650nm / B: AR 650-950nm / C: AR 950-1250nm"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "bk7-plano-concave-cylindrical-lenses"
    },
    {
        "id": 13,
        "name": "UV Fused Silica Plano-Convex Cylindrical Lenses",
        "nameZh": "UV熔融石英平凸柱面透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "UV fused silica plano-convex cylindrical lenses offer high transmittance in the 195-2100nm range. Ideal for UV wavelength laser applications. Custom designs available.",
        "descriptionZh": "UV熔融石英平凸柱面透镜在195nm-2100nm波段有较高透过率，是紫外波段透镜的理想选择。可定制。",
        "image": "images/products/optical-lenses/uv-fused-silica-plano-convex-cylindrical-lenses.jpg",
        "parameters": {
            "material": "UV Fused Silica (JGS1)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "Custom Design"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "uv-fused-silica-plano-convex-cylindrical-lenses"
    },
    {
        "id": 14,
        "name": "UV Fused Silica Plano-Concave Cylindrical Lenses",
        "nameZh": "UV熔融石英平凹柱面透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "UV fused silica plano-concave cylindrical lenses feature high transmittance from 195-2100nm. Multiple sizes available, custom orders welcome.",
        "descriptionZh": "UV熔融石英平凹柱面透镜在195-2100nm波长范围内有较高透过率。可提供多种尺寸规格，接受定制。",
        "image": "images/products/optical-lenses/uv-fused-silica-plano-concave-cylindrical-lenses.jpg",
        "parameters": {
            "material": "UV Fused Silica (JGS1)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "Custom Design"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "uv-fused-silica-plano-concave-cylindrical-lenses"
    },
    {
        "id": 15,
        "name": "Achromatic Doublet Lenses",
        "nameZh": "消色差双胶合透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "Achromatic doublet lenses consist of a low-dispersion crown glass positive lens cemented to a high-dispersion flint glass negative lens. They have much less spherical aberration compared to single lenses.",
        "descriptionZh": "消色差双胶合透镜由低分散的冕牌玻璃正透镜和高分散的火石玻璃负透镜胶合而成，球差比单透镜小得多。",
        "image": "images/products/optical-lenses/achromatic-doublet-lenses.jpg",
        "parameters": {
            "material": "K9/ZF2",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "A: AR 350-650nm / B: AR 650-950nm / C: AR 950-1250nm"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "achromatic-doublet-lenses"
    },
    {
        "id": 16,
        "name": "BK7 C-Lenses",
        "nameZh": "BK7 C-透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "BK7 C-lenses are mainly used for fiber optic beam collimation, isolation, and conversion. Compared to other lenses, C-lenses offer lower cost, lower insertion loss at long working distances, and wider operating ranges.",
        "descriptionZh": "BK7 C-透镜主要用于光纤光束准直、隔离和转换。相比其他透镜价格更低，长工作距离插入损耗更低，工作范围更宽。",
        "image": "images/products/optical-lenses/bk7-c-lenses.jpg",
        "parameters": {
            "material": "K9 (BK7)",
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "focal_length_tolerance": "±1%",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "A: AR 350-650nm / B: AR 650-950nm / C: AR 950-1250nm"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "bk7-c-lenses"
    },
    {
        "id": 17,
        "name": "BK7 Ball Lenses",
        "nameZh": "BK7球透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "BK7 ball lenses are primarily used in laser collimation, focusing, laser-to-fiber coupling, fiber-to-fiber coupling, and fiber-to-detector coupling applications.",
        "descriptionZh": "BK7球透镜主要应用于激光准直、聚焦，激光和光纤耦合，光纤与光纤耦合，光纤和检测器耦合。",
        "image": "images/products/optical-lenses/bk7-ball-lenses.jpg",
        "parameters": {
            "material": "H-K9L (BK7)",
            "diameter_tolerance": "±0.15mm",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "bk7-ball-lenses"
    },
    {
        "id": 18,
        "name": "UV Fused Silica Ball Lenses",
        "nameZh": "UV熔融石英球透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "UV fused silica ball lenses provide superior transmittance from 185-2500nm. Ideal for fiber optic coupling, endoscopy, and laser diode collimation in UV applications.",
        "descriptionZh": "UV熔融石英球透镜在185-2500nm波段具有卓越透过率，适用于紫外应用中的光纤耦合、内窥镜和激光二极管准直。",
        "image": "images/products/optical-lenses/uv-fused-silica-ball-lenses.jpg",
        "parameters": {
            "material": "UV Fused Silica (JGS1)",
            "diameter_tolerance": "±0.15mm",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "clear_aperture": ">90%"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "uv-fused-silica-ball-lenses"
    },
    {
        "id": 19,
        "name": "BK7 Rod Lenses",
        "nameZh": "BK7棒镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "BK7 rod lenses are primarily used to focus a light spot into a line spot. Both ends can be polished for use as light guides. Multiple sizes available.",
        "descriptionZh": "BK7棒镜主要用于将光斑聚焦成线光斑，两端抛光后也可作为导光棒。可提供多种尺寸。",
        "image": "images/products/optical-lenses/bk7-rod-lenses.jpg",
        "parameters": {
            "material": "H-K9L (BK7)",
            "diameter_tolerance": "±0.15mm",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "bk7-rod-lenses"
    },
    {
        "id": 20,
        "name": "UV Fused Silica Rod Lenses",
        "nameZh": "UV熔融石英棒镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "UV fused silica rod lenses offer excellent UV transmission (185-2500nm). Used for focusing light into line spots and as light guides in UV applications.",
        "descriptionZh": "UV熔融石英棒镜在185-2500nm波段具有优异透过率。用于紫外应用中光斑聚焦成线光斑及导光。",
        "image": "images/products/optical-lenses/uv-fused-silica-rod-lenses.jpg",
        "parameters": {
            "material": "UV Fused Silica (JGS1)",
            "diameter_tolerance": "±0.15mm",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "clear_aperture": ">90%"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "uv-fused-silica-rod-lenses"
    },
    {
        "id": 21,
        "name": "Aspherical Lenses",
        "nameZh": "非球面透镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "Aspherical lenses feature non-spherical surfaces, available in multiple sizes, focal lengths, and materials. Custom orders accepted.",
        "descriptionZh": "非球面透镜的面是非球面的，可提供多种尺寸、焦距和材料，同时接受定制。",
        "image": "images/products/optical-lenses/aspherical-lenses.jpg",
        "parameters": {
            "diameter_tolerance": "±0.15mm",
            "thickness_tolerance": "±0.10mm",
            "surface_quality": "40-20",
            "surface_flatness": "λ/4 @632.8nm",
            "centration": "<3 arc min",
            "clear_aperture": ">90%",
            "beveling": "0.25mm×45°",
            "coatings": "A: AR 350-650nm / B: AR 650-950nm / C: AR 950-1250nm"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "aspherical-lenses"
    },
    {
        "id": 22,
        "name": "Laser Beam Expanders",
        "nameZh": "激光扩束镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "Laser beam expanders are available for wavelengths from 266nm to 1064nm with expansion ratios of 2x to 15x. Designed for precision laser applications.",
        "descriptionZh": "激光扩束镜覆盖266nm至1064nm波长，放大倍率2x至15x，专为精密激光应用设计。",
        "image": "images/products/optical-lenses/laser-beam-expanders.jpg",
        "parameters": {
            "wavelength_range": "266-1064nm",
            "expansion_ratio": "2x to 15x",
            "max_input_spot": "15mm",
            "max_output_spot": "36mm"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "laser-beam-expanders"
    },
    {
        "id": 23,
        "name": "Microscope Objectives",
        "nameZh": "显微物镜",
        "category": "Optical Lenses",
        "categoryZh": "光学透镜",
        "description": "Microscope objectives available in 4x, 10x, 20x, 40x, 60x, and 100x magnifications with parfocal distance of 45mm and conjugate focal distance of 195mm.",
        "descriptionZh": "显微物镜提供4x、10x、20x、40x、60x和100x放大倍数，齐焦距离45mm，共轭焦距195mm。",
        "image": "images/products/optical-lenses/microscope-objectives.jpg",
        "parameters": {
            "magnification": "4X, 10X, 20X, 40X, 60X, 100X",
            "numerical_aperture": "0.1-1.25",
            "parfocal_distance": "45mm",
            "conjugate_focal_distance": "195mm"
        },
        "price": 0,
        "priceUnit": "USD",
        "priceNote": "Contact for pricing",
        "priceNoteZh": "询价",
        "slug": "microscope-objectives"
    },
]

# Continue with Windows, Mirrors, Prisms, Filters, Beamsplitters, Wave Plates, Polarizers, Laser Protection
# ... (will be added in the full script)

# Write to file
import json

output = "// PhotonEdge Products Data V34\n// Rebuilt from official product catalog\n// Contains all product information for the website\n\nvar PRODUCTS = "
output += json.dumps(products, indent=2, ensure_ascii=False)
output += ";\n"

print(f"Generated {len(products)} products so far (lenses only)")
print("Need to add: Windows, Mirrors, Prisms, Filters, Beamsplitters, Wave Plates, Polarizers, Laser Protection")
