// Products Data for PhotonEdge Optics
// Website: photonedgeoptics.com
// Email: sales@photonedgeoptics.com
// Tel: +86-13693009175
// 
// This file contains all optical components product data
// Categories: Lenses, Windows, Mirrors, Prisms, Filters, Beamsplitters, Waveplates, Polarizers
// 
// Last Updated: 2025

const PRODUCTS = [
  // =====================================================
  // OPTICAL LENSES - K9 Plano-Convex Lenses
  // =====================================================
  {
    id: "lens-k9-plano-convex-lopcxb2.5-3.9",
    name: "BK7 Plano-Convex Lens LOPCXB2.5-3.9",
    nameZh: "K9平凸透镜 LOPCXB2.5-3.9",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "High-quality BK7 (K9) plano-convex lens with 2.5mm diameter and 3.9mm focal length. Ideal for light focusing and collimation in scientific, industrial, and research applications. Features excellent optical clarity in the 350-700nm range with anti-reflection coating options. Precision manufactured with λ/4 surface flatness and 40-20 scratch-dig surface quality.",
    image: "images/products/optical-lenses/bk7-plano-convex.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "2.5mm",
      focalLength: "3.9mm",
      centerThickness: "1.95mm",
      diameterTolerance: "±0.15mm",
      focalLengthTolerance: "±1%",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating 350-700nm (Standard)"
    },
    partNumbers: ["LOPCXB2.5-3.9"],
    price: 8,
    priceUnit: "USD",
    priceNote: "Price varies by coating option",
    priceNoteZh: "价格因镀膜选项不同而异",
    slug: "bk7-plano-convex-2.5mm-3.9mm"
  },
  {
    id: "lens-k9-plano-convex-lopcxb5.0-10",
    name: "BK7 Plano-Convex Lens LOPCXB5.0-10",
    nameZh: "K9平凸透镜 LOPCXB5.0-10",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "High-quality BK7 (K9) plano-convex lens with 5.0mm diameter and 10.0mm focal length. Ideal for light focusing and collimation in scientific, industrial, and research applications. Features excellent optical clarity in the 350-700nm range with anti-reflection coating options. Precision manufactured with λ/4 surface flatness and 40-20 scratch-dig surface quality.",
    image: "images/products/optical-lenses/bk7-plano-convex.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "5.0mm",
      focalLength: "10.0mm",
      centerThickness: "2.0mm",
      diameterTolerance: "±0.15mm",
      focalLengthTolerance: "±1%",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating 350-700nm (Standard)"
    },
    partNumbers: ["LOPCXB5.0-10"],
    price: 8,
    priceUnit: "USD",
    priceNote: "Price varies by coating option",
    priceNoteZh: "价格因镀膜选项不同而异",
    slug: "bk7-plano-convex-5mm-10mm"
  },
  {
    id: "lens-k9-plano-convex-lopcxb10-15",
    name: "BK7 Plano-Convex Lens LOPCXB10-15",
    nameZh: "K9平凸透镜 LOPCXB10-15",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "High-quality BK7 (K9) plano-convex lens with 10.0mm diameter and 15.0mm focal length. Ideal for light focusing and collimation in scientific, industrial, and research applications. Features excellent optical clarity in the 350-700nm range with anti-reflection coating options. Precision manufactured with λ/4 surface flatness and 40-20 scratch-dig surface quality.",
    image: "images/products/optical-lenses/bk7-plano-convex.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "10.0mm",
      focalLength: "15.0mm",
      centerThickness: "3.8mm",
      diameterTolerance: "±0.15mm",
      focalLengthTolerance: "±1%",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating 350-700nm (Standard)"
    },
    partNumbers: ["LOPCXB10-15"],
    price: 8,
    priceUnit: "USD",
    priceNote: "Price varies by coating option",
    priceNoteZh: "价格因镀膜选项不同而异",
    slug: "bk7-plano-convex-10mm-15mm"
  },
  {
    id: "lens-k9-plano-convex-lopcxb12.7-25.4",
    name: "BK7 Plano-Convex Lens LOPCXB12.7-25.4",
    nameZh: "K9平凸透镜 LOPCXB12.7-25.4",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "High-quality BK7 (K9) plano-convex lens with 12.7mm (1/2 inch) diameter and 25.4mm focal length. Industry standard 1/2 inch format. Precision manufactured with λ/4 surface flatness and 40-20 scratch-dig surface quality. Perfect for optical experiments, laser systems, and imaging applications.",
    image: "images/products/optical-lenses/bk7-plano-convex.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "12.7mm (1/2 inch)",
      focalLength: "25.4mm",
      centerThickness: "4.0mm",
      diameterTolerance: "±0.15mm",
      focalLengthTolerance: "±1%",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating 350-700nm (Standard)"
    },
    partNumbers: ["LOPCXB12.7-25.4"],
    price: 8,
    priceUnit: "USD",
    priceNote: "Price varies by coating option",
    priceNoteZh: "价格因镀膜选项不同而异",
    slug: "bk7-plano-convex-12.7mm-25.4mm"
  },
  {
    id: "lens-k9-plano-convex-lopcxb25-50",
    name: "BK7 Plano-Convex Lens LOPCXB25-50",
    nameZh: "K9平凸透镜 LOPCXB25-50",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "High-quality BK7 (K9) plano-convex lens with 25.0mm diameter and 50.0mm focal length. 2 inch format compatible with standard optical mounts. Features excellent optical clarity with anti-reflection coating options for maximum transmission. Precision manufactured for scientific and industrial applications.",
    image: "images/products/optical-lenses/bk7-plano-convex.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "25.0mm",
      focalLength: "50.0mm",
      centerThickness: "5.2mm",
      diameterTolerance: "±0.15mm",
      focalLengthTolerance: "±1%",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating 350-700nm (Standard)"
    },
    partNumbers: ["LOPCXB25-50"],
    price: 12,
    priceUnit: "USD",
    priceNote: "Price varies by coating option",
    priceNoteZh: "价格因镀膜选项不同而异",
    slug: "bk7-plano-convex-25mm-50mm"
  },
  {
    id: "lens-k9-plano-convex-lopcxb25.4-100",
    name: "BK7 Plano-Convex Lens LOPCXB25.4-100",
    nameZh: "K9平凸透镜 LOPCXB25.4-100",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "High-quality BK7 (K9) plano-convex lens with 25.4mm (1 inch) diameter and 100mm focal length. Industry standard 1 inch format. Long focal length design for collimation and imaging applications. Precision manufactured with λ/4 surface flatness and 40-20 scratch-dig surface quality.",
    image: "images/products/optical-lenses/bk7-plano-convex.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "25.4mm (1 inch)",
      focalLength: "100.0mm",
      centerThickness: "3.5mm",
      diameterTolerance: "±0.15mm",
      focalLengthTolerance: "±1%",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating 350-700nm (Standard)"
    },
    partNumbers: ["LOPCXB25.4-100"],
    price: 12,
    priceUnit: "USD",
    priceNote: "Price varies by coating option",
    priceNoteZh: "价格因镀膜选项不同而异",
    slug: "bk7-plano-convex-25.4mm-100mm"
  },
  {
    id: "lens-k9-plano-convex-lopcxb50.8-100",
    name: "BK7 Plano-Convex Lens LOPCXB50.8-100",
    nameZh: "K9平凸透镜 LOPCXB50.8-100",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "High-quality BK7 (K9) plano-convex lens with 50.8mm (2 inch) diameter and 100mm focal length. Large format 2 inch diameter for high-power laser and imaging applications. Features excellent thermal stability and optical quality. AR coating available for enhanced transmission.",
    image: "images/products/optical-lenses/bk7-plano-convex.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "50.8mm (2 inch)",
      focalLength: "100.0mm",
      centerThickness: "9.7mm",
      diameterTolerance: "±0.15mm",
      focalLengthTolerance: "±1%",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating 350-700nm (Standard)"
    },
    partNumbers: ["LOPCXB50.8-100"],
    price: 18,
    priceUnit: "USD",
    priceNote: "Price varies by coating option",
    priceNoteZh: "价格因镀膜选项不同而异",
    slug: "bk7-plano-convex-50.8mm-100mm"
  },
  {
    id: "lens-k9-bi-convex-lobcxb10-15",
    name: "BK7 Bi-Convex Lens LOBCXB10-15",
    nameZh: "K9双凸透镜 LOBCXB10-15",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "Premium BK7 (K9) bi-convex lens featuring 10mm diameter and 15mm focal length. Symmetrical double convex surfaces minimize spherical aberration. Designed for optical imaging, light collimation, and focusing applications. Manufactured with high precision tolerances for scientific and industrial use.",
    image: "images/products/optical-lenses/bk7-bi-convex.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "10.0mm",
      focalLength: "15.0mm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating available"
    },
    partNumbers: ["LOBCXB10-15"],
    price: 8,
    priceUnit: "USD",
    priceNote: "Price varies by coating option",
    priceNoteZh: "价格因镀膜选项不同而异",
    slug: "bk7-bi-convex-10mm-15mm"
  },
  {
    id: "lens-k9-bi-convex-lobcxb12.7-25",
    name: "BK7 Bi-Convex Lens LOBCXB12.7-25",
    nameZh: "K9双凸透镜 LOBCXB12.7-25",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "Premium BK7 (K9) bi-convex lens featuring 12.7mm (1/2 inch) diameter and 25mm focal length. Industry standard format with symmetrical double convex surfaces. Designed for optical imaging, light collimation, and focusing applications. Manufactured with high precision tolerances.",
    image: "images/products/optical-lenses/bk7-bi-convex.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "12.7mm (1/2 inch)",
      focalLength: "25.0mm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating available"
    },
    partNumbers: ["LOBCXB12.7-25"],
    price: 8,
    priceUnit: "USD",
    priceNote: "Price varies by coating option",
    priceNoteZh: "价格因镀膜选项不同而异",
    slug: "bk7-bi-convex-12.7mm-25mm"
  },
  {
    id: "lens-k9-bi-convex-lobcxb25.4-50",
    name: "BK7 Bi-Convex Lens LOBCXB25.4-50",
    nameZh: "K9双凸透镜 LOBCXB25.4-50",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "Premium BK7 (K9) bi-convex lens featuring 25.4mm (1 inch) diameter and 50mm focal length. 1 inch industry standard format with symmetrical double convex surfaces. Designed for optical imaging, light collimation, and focusing applications. Manufactured with high precision tolerances for scientific and industrial use.",
    image: "images/products/optical-lenses/bk7-bi-convex.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "25.4mm (1 inch)",
      focalLength: "50.0mm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating available"
    },
    partNumbers: ["LOBCXB25.4-50"],
    price: 12,
    priceUnit: "USD",
    priceNote: "Price varies by coating option",
    priceNoteZh: "价格因镀膜选项不同而异",
    slug: "bk7-bi-convex-25.4mm-50mm"
  },
  {
    id: "lens-k9-bi-convex-lobcxb25.4-100",
    name: "BK7 Bi-Convex Lens LOBCXB25.4-100",
    nameZh: "K9双凸透镜 LOBCXB25.4-100",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "Premium BK7 (K9) bi-convex lens featuring 25.4mm (1 inch) diameter and 100mm focal length. Long focal length design for imaging and collimation applications. Symmetrical double convex surfaces minimize spherical aberration. Manufactured with high precision tolerances.",
    image: "images/products/optical-lenses/bk7-bi-convex.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "25.4mm (1 inch)",
      focalLength: "100.0mm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating available"
    },
    partNumbers: ["LOBCXB25.4-100"],
    price: 12,
    priceUnit: "USD",
    priceNote: "Price varies by coating option",
    priceNoteZh: "价格因镀膜选项不同而异",
    slug: "bk7-bi-convex-25.4mm-100mm"
  },
  {
    id: "lens-k9-plano-concave-lopccb10-20",
    name: "BK7 Plano-Concave Lens LOPCCB10-20",
    nameZh: "K9平凹透镜 LOPCCB10-20",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "High-performance BK7 (K9) plano-concave lens with 10mm diameter and -20mm negative focal length. Perfect for light divergence and beam expansion applications. Precision ground surfaces ensure excellent optical quality with uniform material properties.",
    image: "images/products/optical-lenses/bk7-plano-concave.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "10.0mm",
      focalLength: "-20.0mm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating available"
    },
    partNumbers: ["LOPCCB10-20"],
    price: 10,
    priceUnit: "USD",
    priceNote: "Price varies by coating option",
    priceNoteZh: "价格因镀膜选项不同而异",
    slug: "bk7-plano-concave-10mm"
  },
  {
    id: "lens-k9-plano-concave-lopccb25.4-50",
    name: "BK7 Plano-Concave Lens LOPCCB25.4-50",
    nameZh: "K9平凹透镜 LOPCCB25.4-50",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "High-performance BK7 (K9) plano-concave lens with 25.4mm diameter and -50mm negative focal length. 1 inch format for beam expansion and divergence applications. Precision ground surfaces ensure excellent optical quality.",
    image: "images/products/optical-lenses/bk7-plano-concave.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "25.4mm",
      focalLength: "-50.0mm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating available"
    },
    partNumbers: ["LOPCCB25.4-50"],
    price: 15,
    priceUnit: "USD",
    priceNote: "Price varies by coating option",
    priceNoteZh: "价格因镀膜选项不同而异",
    slug: "bk7-plano-concave-25.4mm"
  },
  {
    id: "lens-k9-meniscus-positive-lopm25.4-100",
    name: "BK7 Positive Meniscus Lens LOPM25.4-100",
    nameZh: "K9正弯月透镜 LOPM25.4-100",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "BK7 positive meniscus lens with 25.4mm diameter and 100mm focal length. Positive meniscus lenses have a convex surface on one side and concave on the other, with the center thicker than the edges. Used to reduce spherical aberration when combined with other lenses.",
    image: "images/products/optical-lenses/bk7-meniscus.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "25.4mm",
      focalLength: "100.0mm",
      centerThickness: "3.6mm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      centration: "<3 arc min",
      coating: "AR Coating 350-700nm (Standard)"
    },
    partNumbers: ["LOPM25.4-100"],
    price: 15,
    priceUnit: "USD",
    priceNote: "Custom focal lengths available",
    priceNoteZh: "可提供定制焦距",
    slug: "bk7-positive-meniscus-25.4mm-100mm"
  },
  {
    id: "lens-k9-meniscus-negative-lonm25.4-100",
    name: "BK7 Negative Meniscus Lens LONM25.4-100",
    nameZh: "K9负弯月透镜 LONM25.4-100",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "BK7 negative meniscus lens with 25.4mm diameter and -100mm focal length. Negative meniscus lenses have a concave surface on one side and convex on the other, with the center thinner than the edges. Used to reduce spherical aberration and numerical aperture in optical systems.",
    image: "images/products/optical-lenses/bk7-meniscus.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "25.4mm",
      focalLength: "-100.0mm",
      centerThickness: "3.0mm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      centration: "<3 arc min",
      coating: "AR Coating available"
    },
    partNumbers: ["LONM25.4-100"],
    price: 15,
    priceUnit: "USD",
    priceNote: "Custom focal lengths available",
    priceNoteZh: "可提供定制焦距",
    slug: "bk7-negative-meniscus-25.4mm-100mm"
  },
  {
    id: "lens-uv-fused-silica-plano-convex-lopcxf10-25",
    name: "UV Fused Silica Plano-Convex Lens LOPCXF10-25",
    nameZh: "紫外融石英平凸透镜 LOPCXF10-25",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "Premium UV Fused Silica plano-convex lens designed for UV-visible-near IR applications (195-2100nm). 10mm diameter and 25mm focal length. Ideal for UV laser systems, spectroscopy, and high-power laser applications with superior UV transmission.",
    image: "images/products/optical-lenses/uv-fused-silica-plano-convex.jpg",
    parameters: {
      material: "UV Fused Silica (JGS1)",
      diameter: "10.0mm",
      focalLength: "25.0mm",
      wavelengthRange: "195-2100nm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Custom Design"
    },
    partNumbers: ["LOPCXF10-25"],
    price: 15,
    priceUnit: "USD",
    priceNote: "Custom coatings available",
    priceNoteZh: "可提供定制镀膜",
    slug: "uv-fused-silica-plano-convex-10mm-25mm"
  },
  {
    id: "lens-uv-fused-silica-plano-convex-lopcxf25.4-50",
    name: "UV Fused Silica Plano-Convex Lens LOPCXF25.4-50",
    nameZh: "紫外融石英平凸透镜 LOPCXF25.4-50",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "Premium UV Fused Silica plano-convex lens designed for UV-visible-near IR applications (195-2100nm). 25.4mm (1 inch) diameter and 50mm focal length. 1 inch format compatible with standard mounts. Ideal for UV laser systems, spectroscopy, and high-power laser applications.",
    image: "images/products/optical-lenses/uv-fused-silica-plano-convex.jpg",
    parameters: {
      material: "UV Fused Silica (JGS1)",
      diameter: "25.4mm (1 inch)",
      focalLength: "50.0mm",
      wavelengthRange: "195-2100nm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Custom Design"
    },
    partNumbers: ["LOPCXF25.4-50"],
    price: 22,
    priceUnit: "USD",
    priceNote: "Custom coatings available",
    priceNoteZh: "可提供定制镀膜",
    slug: "uv-fused-silica-plano-convex-25.4mm-50mm"
  },
  {
    id: "lens-achromatic-loadl25-75",
    name: "Achromatic Doublet Lens LOADL25-75",
    nameZh: "消色差双胶合透镜 LOADL25-75",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "Premium achromatic doublet lens with 25mm diameter and 75mm focal length. K9/ZF2 design corrects chromatic aberration for two wavelengths. Perfect for color-critical imaging, photometry, and white light applications. Minimizes spherical aberration at infinite conjugate ratio.",
    image: "images/products/optical-lenses/achromatic-doublet.jpg",
    parameters: {
      material: "K9/ZF2 Doublet",
      diameter: "25.0mm",
      focalLength: "75.0mm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating 350-700nm (Standard)"
    },
    partNumbers: ["LOADL25-75"],
    price: 85,
    priceUnit: "USD",
    priceNote: "Custom focal lengths available",
    priceNoteZh: "可提供定制焦距",
    slug: "achromatic-doublet-25mm-75mm"
  },
  {
    id: "lens-achromatic-loadl25.4-50",
    name: "Achromatic Doublet Lens LOADL25.4-50",
    nameZh: "消色差双胶合透镜 LOADL25.4-50",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "Premium achromatic doublet lens with 25.4mm (1 inch) diameter and 50mm focal length. K9/ZF2 design corrects chromatic aberration for two wavelengths. 1 inch format for scientific imaging and color-critical applications. Minimizes spherical aberration.",
    image: "images/products/optical-lenses/achromatic-doublet.jpg",
    parameters: {
      material: "K9/ZF2 Doublet",
      diameter: "25.4mm (1 inch)",
      focalLength: "50.0mm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating 350-700nm (Standard)"
    },
    partNumbers: ["LOADL25.4-50"],
    price: 85,
    priceUnit: "USD",
    priceNote: "Custom focal lengths available",
    priceNoteZh: "可提供定制焦距",
    slug: "achromatic-doublet-25.4mm-50mm"
  },
  {
    id: "lens-c-lens-locl13",
    name: "BK7 C-Lens for Fiber LOCL13",
    nameZh: "K9 C透镜光纤耦合 LOCL13",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "BK7 C-lens optimized for fiber optic collimation and coupling at 1310nm. 1.8mm diameter format. Features low insertion loss, wide working range, and cost-effective design for telecom and fiber sensing applications.",
    image: "images/products/optical-lenses/c-lens.jpg",
    parameters: {
      material: "BK7",
      diameter: "1.8mm",
      wavelength: "1310nm",
      wedgeAngle: "8°",
      surfaceQuality: "40-20",
      coating: "AR Coating available"
    },
    partNumbers: ["LOCL13"],
    price: 15,
    priceUnit: "USD",
    priceNote: "1310nm and 1550nm versions",
    priceNoteZh: "1310nm和1550nm版本",
    slug: "c-lens-1.8mm-1310nm"
  },
  {
    id: "lens-ball-lobl3.0",
    name: "BK7 Ball Lens LOBL3.0",
    nameZh: "K9球透镜 LOBL3.0",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "High-quality BK7 ball lens with 3.0mm diameter. Perfect for laser-to-fiber coupling, fiber-to-fiber coupling, and laser focusing. Features 360° symmetry for easy alignment and excellent optical quality.",
    image: "images/products/optical-lenses/ball-lens.jpg",
    parameters: {
      material: "BK7",
      diameter: "3.0mm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      sphericity: "High precision"
    },
    partNumbers: ["LOBL3.0"],
    price: 5,
    priceUnit: "USD",
    priceNote: "Sapphire and silica versions available",
    priceNoteZh: "可提供蓝宝石和石英版本",
    slug: "ball-lens-3mm"
  },
  {
    id: "lens-ball-lobl6.0",
    name: "BK7 Ball Lens LOBL6.0",
    nameZh: "K9球透镜 LOBL6.0",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "High-quality BK7 ball lens with 6.0mm diameter. Larger format for higher power laser coupling applications. Perfect for laser-to-fiber coupling, fiber-to-fiber coupling, and laser focusing. Features 360° symmetry for easy alignment.",
    image: "images/products/optical-lenses/ball-lens.jpg",
    parameters: {
      material: "BK7",
      diameter: "6.0mm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      sphericity: "High precision"
    },
    partNumbers: ["LOBL6.0"],
    price: 8,
    priceUnit: "USD",
    priceNote: "Sapphire and silica versions available",
    priceNoteZh: "可提供蓝宝石和石英版本",
    slug: "ball-lens-6mm"
  },
  {
    id: "lens-rod-lorl10-20",
    name: "BK7 Rod Lens LORL10-20",
    nameZh: "K9棒镜 LORL10-20",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "BK7 rod lens (10mm x 20mm) for line light generation. Polished ends allow use as light guides. Ideal for illumination systems, barcode scanning, and linear beam shaping applications.",
    image: "images/products/optical-lenses/rod-lens.jpg",
    parameters: {
      material: "BK7",
      diameter: "10.0mm",
      length: "20.0mm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      endFinish: "Both ends polished"
    },
    partNumbers: ["LORL10-20"],
    price: 18,
    priceUnit: "USD",
    priceNote: "Custom lengths available",
    priceNoteZh: "可提供定制长度",
    slug: "rod-lens-10mm-x-20mm"
  },
  {
    id: "lens-aspherical-loal18-12.0",
    name: "Aspherical Lens LOAL18-12.0",
    nameZh: "非球面透镜 LOAL18-12.0",
    category: "optical-lenses",
    categoryZh: "光学透镜",
    description: "Precision aspherical lens for laser diode collimation and fiber coupling. 18mm diameter, 12mm focal length. B270 glass construction eliminates spherical aberration. Superior performance for critical focusing applications.",
    image: "images/products/optical-lenses/aspherical-lens.jpg",
    parameters: {
      material: "B270",
      diameter: "18.0mm",
      focalLength: "12.0mm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      numericalAperture: "High",
      coating: "AR Coating available"
    },
    partNumbers: ["LOAL18-12.0"],
    price: 28,
    priceUnit: "USD",
    priceNote: "Custom NA and focal length available",
    priceNoteZh: "可提供定制NA和焦距",
    slug: "aspherical-lens-18mm"
  },

  // =====================================================
  // OPTICAL WINDOWS
  // =====================================================
  {
    id: "window-k9-lowb10-3",
    name: "BK7 Window LOWB10-3",
    nameZh: "K9窗口 LOWB10-3",
    category: "optical-windows",
    categoryZh: "光学窗口",
    description: "High-quality BK7 (K9) optical window with 10mm diameter and 3mm thickness. Offers excellent transmission from 330nm to 2100nm with >99.5% transmission when anti-reflection coated. Ideal for optical instrumentation, laser systems, and scientific research applications.",
    image: "images/products/optical-windows/bk7-window.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "10.0mm",
      thickness: "3.0mm",
      wavelengthRange: "330-2100nm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating available"
    },
    partNumbers: ["LOWB10-3"],
    price: 5,
    priceUnit: "USD",
    priceNote: "Custom sizes available",
    priceNoteZh: "可提供定制尺寸",
    slug: "bk7-window-10mm"
  },
  {
    id: "window-k9-lowb25.4-3",
    name: "BK7 Window LOWB25.4-3",
    nameZh: "K9窗口 LOWB25.4-3",
    category: "optical-windows",
    categoryZh: "光学窗口",
    description: "High-quality BK7 (K9) optical window with 25.4mm (1 inch) diameter and 3mm thickness. 1 inch standard format. Offers excellent transmission from 330nm to 2100nm with >99.5% transmission when anti-reflection coated. Ideal for optical instrumentation, laser systems, and scientific research.",
    image: "images/products/optical-windows/bk7-window.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "25.4mm (1 inch)",
      thickness: "3.0mm",
      wavelengthRange: "330-2100nm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating available"
    },
    partNumbers: ["LOWB25.4-3"],
    price: 8,
    priceUnit: "USD",
    priceNote: "Custom sizes available",
    priceNoteZh: "可提供定制尺寸",
    slug: "bk7-window-25.4mm"
  },
  {
    id: "window-k9-lowb50.8-5",
    name: "BK7 Window LOWB50.8-5",
    nameZh: "K9窗口 LOWB50.8-5",
    category: "optical-windows",
    categoryZh: "光学窗口",
    description: "High-quality BK7 (K9) optical window with 50.8mm (2 inch) diameter and 5mm thickness. Large format 2 inch for laser windows and optical instrumentation. Offers excellent transmission from 330nm to 2100nm. AR coating available for maximum transmission.",
    image: "images/products/optical-windows/bk7-window.jpg",
    parameters: {
      material: "BK7 (K9)",
      diameter: "50.8mm (2 inch)",
      thickness: "5.0mm",
      wavelengthRange: "330-2100nm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "AR Coating available"
    },
    partNumbers: ["LOWB50.8-5"],
    price: 12,
    priceUnit: "USD",
    priceNote: "Custom sizes available",
    priceNoteZh: "可提供定制尺寸",
    slug: "bk7-window-50.8mm"
  },
  {
    id: "window-uv-fused-silica-lowf10-3",
    name: "UV Fused Silica Window LOWF10-3",
    nameZh: "紫外融石英窗口 LOWF10-3",
    category: "optical-windows",
    categoryZh: "光学窗口",
    description: "Premium UV Fused Silica optical window (JGS1) with 10mm diameter and 3mm thickness. Superior UV transmission from 185nm to 2100nm. Perfect for UV laser applications, excimer lasers, and semiconductor processing equipment.",
    image: "images/products/optical-windows/uv-fused-silica-window.jpg",
    parameters: {
      material: "UV Fused Silica (JGS1)",
      diameter: "10.0mm",
      thickness: "3.0mm",
      wavelengthRange: "185-2100nm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Custom Design"
    },
    partNumbers: ["LOWF10-3"],
    price: 12,
    priceUnit: "USD",
    priceNote: "Custom coatings available",
    priceNoteZh: "可提供定制镀膜",
    slug: "uv-fused-silica-window-10mm"
  },
  {
    id: "window-uv-fused-silica-lowf25.4-3",
    name: "UV Fused Silica Window LOWF25.4-3",
    nameZh: "紫外融石英窗口 LOWF25.4-3",
    category: "optical-windows",
    categoryZh: "光学窗口",
    description: "Premium UV Fused Silica optical window (JGS1) with 25.4mm (1 inch) diameter and 3mm thickness. Superior UV transmission from 185nm to 2100nm. 1 inch format. Perfect for UV laser applications, excimer lasers, and semiconductor processing.",
    image: "images/products/optical-windows/uv-fused-silica-window.jpg",
    parameters: {
      material: "UV Fused Silica (JGS1)",
      diameter: "25.4mm (1 inch)",
      thickness: "3.0mm",
      wavelengthRange: "185-2100nm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Custom Design"
    },
    partNumbers: ["LOWF25.4-3"],
    price: 18,
    priceUnit: "USD",
    priceNote: "Custom coatings available",
    priceNoteZh: "可提供定制镀膜",
    slug: "uv-fused-silica-window-25.4mm"
  },
  {
    id: "window-sapphire-lows10-3",
    name: "Sapphire Window LOWS10-3",
    nameZh: "蓝宝石窗口 LOWS10-3",
    category: "optical-windows",
    categoryZh: "光学窗口",
    description: "High-hardness sapphire (Al2O3) optical window with 10mm diameter and 3mm thickness. Features extremely high surface hardness, excellent thermal conductivity, and superior chemical resistance. Wide transmission range from 150nm to 5.5μm. Ideal for harsh environment applications.",
    image: "images/products/optical-windows/sapphire-window.jpg",
    parameters: {
      material: "Sapphire (Al2O3)",
      diameter: "10.0mm",
      thickness: "3.0mm",
      wavelengthRange: "150nm-5.5μm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Custom Design"
    },
    partNumbers: ["LOWS10-3"],
    price: 18,
    priceUnit: "USD",
    priceNote: "Custom coatings available",
    priceNoteZh: "可提供定制镀膜",
    slug: "sapphire-window-10mm"
  },
  {
    id: "window-sapphire-lows25.4-3",
    name: "Sapphire Window LOWS25.4-3",
    nameZh: "蓝宝石窗口 LOWS25.4-3",
    category: "optical-windows",
    categoryZh: "光学窗口",
    description: "High-hardness sapphire (Al2O3) optical window with 25.4mm (1 inch) diameter and 3mm thickness. Features extremely high surface hardness, excellent thermal conductivity, and superior chemical resistance. Wide transmission range from 150nm to 5.5μm. Ideal for harsh environment and high-power laser windows.",
    image: "images/products/optical-windows/sapphire-window.jpg",
    parameters: {
      material: "Sapphire (Al2O3)",
      diameter: "25.4mm (1 inch)",
      thickness: "3.0mm",
      wavelengthRange: "150nm-5.5μm",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Custom Design"
    },
    partNumbers: ["LOWS25.4-3"],
    price: 28,
    priceUnit: "USD",
    priceNote: "Custom coatings available",
    priceNoteZh: "可提供定制镀膜",
    slug: "sapphire-window-25.4mm"
  },
  {
    id: "window-caf2-lowc10-3",
    name: "CaF2 Window LOWC10-3",
    nameZh: "氟化钙窗口 LOWC10-3",
    category: "optical-windows",
    categoryZh: "光学窗口",
    description: "Calcium Fluoride (CaF2) optical window with 10mm diameter and 3mm thickness. Excellent transmission from UV to IR (130nm-8μm). Low absorption, high damage threshold. Ideal for excimer lasers, spectroscopy, and deep UV applications.",
    image: "images/products/optical-windows/caf2-window.jpg",
    parameters: {
      material: "CaF2",
      diameter: "10.0mm",
      thickness: "3.0mm",
      wavelengthRange: "130nm-8μm",
      refractiveIndex: "1.44",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "80-50",
      surfaceFlatness: "λ/2@632.8nm",
      coating: "Custom Design"
    },
    partNumbers: ["LOWC10-3"],
    price: 55,
    priceUnit: "USD",
    priceNote: "Custom sizes and coatings available",
    priceNoteZh: "可提供定制尺寸和镀膜",
    slug: "caf2-window-10mm"
  },
  {
    id: "window-caf2-lowc25.4-3",
    name: "CaF2 Window LOWC25.4-3",
    nameZh: "氟化钙窗口 LOWC25.4-3",
    category: "optical-windows",
    categoryZh: "光学窗口",
    description: "Calcium Fluoride (CaF2) optical window with 25.4mm (1 inch) diameter and 3mm thickness. Excellent transmission from UV to IR (130nm-8μm). Low absorption, high damage threshold. 1 inch format ideal for spectroscopy and deep UV applications.",
    image: "images/products/optical-windows/caf2-window.jpg",
    parameters: {
      material: "CaF2",
      diameter: "25.4mm (1 inch)",
      thickness: "3.0mm",
      wavelengthRange: "130nm-8μm",
      refractiveIndex: "1.44",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "80-50",
      surfaceFlatness: "λ/2@632.8nm",
      coating: "Custom Design"
    },
    partNumbers: ["LOWC25.4-3"],
    price: 85,
    priceUnit: "USD",
    priceNote: "Custom sizes and coatings available",
    priceNoteZh: "可提供定制尺寸和镀膜",
    slug: "caf2-window-25.4mm"
  },
  {
    id: "window-germanium-lowg25.4-3",
    name: "Germanium Window LOWG25.4-3",
    nameZh: "锗窗口 LOWG25.4-3",
    category: "optical-windows",
    categoryZh: "光学窗口",
    description: "High-quality Germanium (Ge) infrared optical window with 25.4mm (1 inch) diameter and 3mm thickness. Optimized for 2-12μm infrared spectrum with high refractive index (n≈4.0). Perfect for thermal imaging, IR spectroscopy, and FLIR systems.",
    image: "images/products/optical-windows/germanium-window.jpg",
    parameters: {
      material: "Germanium (Ge)",
      diameter: "25.4mm (1 inch)",
      thickness: "3.0mm",
      wavelengthRange: "2-12μm",
      refractiveIndex: "4.02",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "60-40",
      surfaceFlatness: "λ/2@632.8nm",
      coating: "Custom Design (AR coating recommended)"
    },
    partNumbers: ["LOWG25.4-3"],
    price: 65,
    priceUnit: "USD",
    priceNote: "AR coating recommended for 8-12μm",
    priceNoteZh: "建议镀8-12μm增透膜",
    slug: "germanium-window-25.4mm"
  },
  {
    id: "window-silicon-lowi25.4-3",
    name: "Silicon Window LOWI25.4-3",
    nameZh: "硅窗口 LOWI25.4-3",
    category: "optical-windows",
    categoryZh: "光学窗口",
    description: "Silicon (Si) infrared window with 25.4mm (1 inch) diameter and 3mm thickness. Excellent transmission 1-7μm and 50-300μm. Low density (2.33 g/cm³) ideal for weight-sensitive IR systems. Perfect for thermal imaging and IR spectroscopy.",
    image: "images/products/optical-windows/silicon-window.jpg",
    parameters: {
      material: "Silicon (Si)",
      diameter: "25.4mm (1 inch)",
      thickness: "3.0mm",
      wavelengthRange: "1-7μm, 50-300μm",
      refractiveIndex: "3.47",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "60-40",
      surfaceFlatness: "λ/2@632.8nm",
      coating: "Custom Design"
    },
    partNumbers: ["LOWI25.4-3"],
    price: 55,
    priceUnit: "USD",
    priceNote: "AR coating available for 3-5μm",
    priceNoteZh: "可提供3-5μm增透膜",
    slug: "silicon-window-25.4mm"
  },
  {
    id: "window-zinc-selenide-lowz25.4-3",
    name: "Zinc Selenide Window LOWZ25.4-3",
    nameZh: "硒化锌窗口 LOWZ25.4-3",
    category: "optical-windows",
    categoryZh: "光学窗口",
    description: "High-power CO2 laser Zinc Selenide (ZnSe) window with 25.4mm (1 inch) diameter and 3mm thickness. Excellent transmission from 500nm to 18μm with low absorption coefficient and high thermal stability. The preferred material for high-power CO2 laser systems.",
    image: "images/products/optical-windows/zinc-selenide-window.jpg",
    parameters: {
      material: "Zinc Selenide (ZnSe)",
      diameter: "25.4mm (1 inch)",
      thickness: "3.0mm",
      wavelengthRange: "500nm-18μm",
      refractiveIndex: "2.48",
      diameterTolerance: "±0.15mm",
      surfaceQuality: "60-40",
      surfaceFlatness: "λ/2@632.8nm",
      coating: "Custom Design"
    },
    partNumbers: ["LOWZ25.4-3"],
    price: 85,
    priceUnit: "USD",
    priceNote: "AR coating available",
    priceNoteZh: "可提供增透膜",
    slug: "zinc-selenide-window-25.4mm"
  },

  // =====================================================
  // OPTICAL MIRRORS
  // =====================================================
  {
    id: "mirror-laser-line-lolpm20-266",
    name: "Laser Line HR Mirror LOLLM20-266",
    nameZh: "激光波长介质高反镜 LOLLM20-266",
    category: "optical-mirrors",
    categoryZh: "光学反射镜",
    description: "Dielectric high-reflectance laser mirror optimized for 266nm UV wavelength. 20mm diameter BK7 substrate with λ/4 surface flatness. Features >99% reflectance with high damage threshold. Ideal for UV laser cavity mirrors and beam steering.",
    image: "images/products/optical-mirrors/laser-line-mirror.jpg",
    parameters: {
      type: "Dielectric HR Mirror",
      wavelength: "266nm",
      reflectance: ">99%",
      diameter: "20mm",
      substrate: "BK7",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Multi-layer dielectric"
    },
    partNumbers: ["LOLLM20-266"],
    price: 22,
    priceUnit: "USD",
    priceNote: "Custom wavelengths available",
    priceNoteZh: "可提供定制波长",
    slug: "laser-hr-mirror-266nm-20mm"
  },
  {
    id: "mirror-laser-line-lolpm20-532",
    name: "Laser Line HR Mirror LOLLM20-532",
    nameZh: "激光波长介质高反镜 LOLLM20-532",
    category: "optical-mirrors",
    categoryZh: "光学反射镜",
    description: "Dielectric high-reflectance laser mirror optimized for 532nm green laser wavelength. 20mm diameter BK7 substrate with λ/4 surface flatness. Features >99% reflectance with high damage threshold. Ideal for Nd:YAG laser cavity mirrors and beam steering.",
    image: "images/products/optical-mirrors/laser-line-mirror.jpg",
    parameters: {
      type: "Dielectric HR Mirror",
      wavelength: "532nm",
      reflectance: ">99%",
      diameter: "20mm",
      substrate: "BK7",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Multi-layer dielectric"
    },
    partNumbers: ["LOLLM20-532"],
    price: 22,
    priceUnit: "USD",
    priceNote: "Custom wavelengths available",
    priceNoteZh: "可提供定制波长",
    slug: "laser-hr-mirror-532nm-20mm"
  },
  {
    id: "mirror-laser-line-lolpm20-1064",
    name: "Laser Line HR Mirror LOLLM20-1064",
    nameZh: "激光波长介质高反镜 LOLLM20-1064",
    category: "optical-mirrors",
    categoryZh: "光学反射镜",
    description: "Dielectric high-reflectance laser mirror optimized for 1064nm Nd:YAG laser wavelength. 20mm diameter BK7 substrate with λ/4 surface flatness. Features >99.5% reflectance with high damage threshold. Ideal for laser cavity mirrors and beam steering applications.",
    image: "images/products/optical-mirrors/laser-line-mirror.jpg",
    parameters: {
      type: "Dielectric HR Mirror",
      wavelength: "1064nm",
      reflectance: ">99.5%",
      diameter: "20mm",
      substrate: "BK7",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Multi-layer dielectric"
    },
    partNumbers: ["LOLLM20-1064"],
    price: 22,
    priceUnit: "USD",
    priceNote: "Custom wavelengths available",
    priceNoteZh: "可提供定制波长",
    slug: "laser-hr-mirror-1064nm-20mm"
  },
  {
    id: "mirror-laser-line-lolpm30-1064",
    name: "Laser Line HR Mirror LOLLM30-1064",
    nameZh: "激光波长介质高反镜 LOLLM30-1064",
    category: "optical-mirrors",
    categoryZh: "光学反射镜",
    description: "Dielectric high-reflectance laser mirror optimized for 1064nm Nd:YAG laser wavelength. 30mm diameter BK7 substrate with λ/4 surface flatness. Larger format for higher power applications. Features >99% reflectance with high damage threshold.",
    image: "images/products/optical-mirrors/laser-line-mirror.jpg",
    parameters: {
      type: "Dielectric HR Mirror",
      wavelength: "1064nm",
      reflectance: ">99%",
      diameter: "30mm",
      substrate: "BK7",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Multi-layer dielectric"
    },
    partNumbers: ["LOLLM30-1064"],
    price: 32,
    priceUnit: "USD",
    priceNote: "Custom wavelengths available",
    priceNoteZh: "可提供定制波长",
    slug: "laser-hr-mirror-1064nm-30mm"
  },
  {
    id: "mirror-broadband-dielectric-lodm25.4-3a1",
    name: "Broadband Dielectric Mirror LODM25.4-3A1",
    nameZh: "宽带介质膜反射镜 LODM25.4-3A1",
    category: "optical-mirrors",
    categoryZh: "光学反射镜",
    description: "Premium broadband dielectric mirror with reflectance >99% over 400-700nm visible range. 25.4mm (1 inch) diameter BK7 substrate with λ/10 surface flatness. Perfect for white light applications, spectroscopy, and broadband laser systems.",
    image: "images/products/optical-mirrors/broadband-dielectric-mirror.jpg",
    parameters: {
      type: "Broadband Dielectric Mirror",
      wavelengthRange: "400-700nm",
      reflectance: ">99%",
      diameter: "25.4mm (1 inch)",
      substrate: "BK7",
      surfaceQuality: "20-10",
      surfaceFlatness: "λ/10@632.8nm",
      coating: "Multi-layer dielectric"
    },
    partNumbers: ["LODM25.4-3A1"],
    price: 38,
    priceUnit: "USD",
    priceNote: "Custom sizes available",
    priceNoteZh: "可提供定制尺寸",
    slug: "broadband-mirror-400-700nm-25.4mm"
  },
  {
    id: "mirror-broadband-dielectric-lodm25.4-4a3",
    name: "Broadband Dielectric Mirror LODM25.4-4A3",
    nameZh: "宽带介质膜反射镜 LODM25.4-4A3",
    category: "optical-mirrors",
    categoryZh: "光学反射镜",
    description: "Premium broadband dielectric mirror with reflectance >99% over 400-1100nm visible to near-IR range. 25.4mm (1 inch) diameter BK7 substrate with λ/10 surface flatness. Perfect for white light applications, spectroscopy, and broadband laser systems.",
    image: "images/products/optical-mirrors/broadband-dielectric-mirror.jpg",
    parameters: {
      type: "Broadband Dielectric Mirror",
      wavelengthRange: "400-1100nm",
      reflectance: ">99%",
      diameter: "25.4mm (1 inch)",
      substrate: "BK7",
      surfaceQuality: "20-10",
      surfaceFlatness: "λ/10@632.8nm",
      coating: "Multi-layer dielectric"
    },
    partNumbers: ["LODM25.4-4A3"],
    price: 38,
    priceUnit: "USD",
    priceNote: "Custom sizes available",
    priceNoteZh: "可提供定制尺寸",
    slug: "broadband-mirror-400-1100nm-25.4mm"
  },
  {
    id: "mirror-protected-aluminum-loalm25.4-3",
    name: "Protected Aluminum Mirror LOALM25.4-3",
    nameZh: "保护铝膜反射镜 LOALM25.4-3",
    category: "optical-mirrors",
    categoryZh: "光学反射镜",
    description: "Protected aluminum mirror with MgF2/SiO coating for enhanced durability. Broadband reflectance >85% over 400-1400nm. 25.4mm (1 inch) diameter BK7 substrate. Ideal for general-purpose reflective applications with excellent value.",
    image: "images/products/optical-mirrors/aluminum-mirror.jpg",
    parameters: {
      type: "Protected Aluminum Mirror",
      wavelengthRange: "400-1400nm",
      reflectance: ">85%",
      diameter: "25.4mm (1 inch)",
      substrate: "BK7",
      surfaceQuality: "60-40",
      surfaceFlatness: "λ/2@632.8nm",
      coating: "Protected Al with MgF2/SiO"
    },
    partNumbers: ["LOALM25.4-3"],
    price: 18,
    priceUnit: "USD",
    priceNote: "Standard sizes in stock",
    priceNoteZh: "标准尺寸现货",
    slug: "protected-aluminum-mirror-25.4mm"
  },
  {
    id: "mirror-protected-silver-loagm25.4-3",
    name: "Protected Silver Mirror LOAGM25.4-3",
    nameZh: "保护银膜反射镜 LOAGM25.4-3",
    category: "optical-mirrors",
    categoryZh: "光学反射镜",
    description: "Protected silver mirror with >95% reflectance across the visible to near-IR spectrum (400-2000nm). 25.4mm (1 inch) diameter BK7 substrate. Excellent for broadband applications including astronomy, IR imaging, and optical metrology.",
    image: "images/products/optical-mirrors/silver-mirror.jpg",
    parameters: {
      type: "Protected Silver Mirror",
      wavelengthRange: "400-2000nm",
      reflectance: ">95%",
      diameter: "25.4mm (1 inch)",
      substrate: "BK7",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Protected Ag"
    },
    partNumbers: ["LOAGM25.4-3"],
    price: 28,
    priceUnit: "USD",
    priceNote: "Custom sizes available",
    priceNoteZh: "可提供定制尺寸",
    slug: "protected-silver-mirror-25.4mm"
  },
  {
    id: "mirror-protected-gold-loaum25.4-3",
    name: "Protected Gold Mirror LOAUM25.4-3",
    nameZh: "保护金膜反射镜 LOAUM25.4-3",
    category: "optical-mirrors",
    categoryZh: "光学反射镜",
    description: "Protected gold mirror optimized for infrared applications with >98% reflectance in the 1-2μm region. 25.4mm (1 inch) diameter BK7 substrate. Essential for IR laser systems, thermal imaging, and FTIR spectroscopy applications.",
    image: "images/products/optical-mirrors/gold-mirror.jpg",
    parameters: {
      type: "Protected Gold Mirror",
      wavelengthRange: "800nm-20μm",
      reflectance: ">98% (1-2μm)",
      diameter: "25.4mm (1 inch)",
      substrate: "BK7",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Protected Au"
    },
    partNumbers: ["LOAUM25.4-3"],
    price: 35,
    priceUnit: "USD",
    priceNote: "Custom sizes available",
    priceNoteZh: "可提供定制尺寸",
    slug: "protected-gold-mirror-25.4mm"
  },

  // =====================================================
  // OPTICAL PRISMS
  // =====================================================
  {
    id: "prism-right-angle-bk7-lorp10-10",
    name: "BK7 Right Angle Prism LORP10-10",
    nameZh: "K9等边直角棱镜 LORP10-10",
    category: "optical-prisms",
    categoryZh: "光学棱镜",
    description: "High-quality BK7 right angle prism with 10mm leg length. Ideal for beam deflection (90°), image erection, and beam steering applications. Features total internal reflection at the hypotenuse face. Precision manufactured with λ/4 surface flatness and ±10 arcsec angle tolerance.",
    image: "images/products/optical-prisms/right-angle-prism.jpg",
    parameters: {
      material: "BK7",
      legLength: "10mm",
      angleTolerance: "±10 arcsec",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Custom (AR coating available)"
    },
    partNumbers: ["LORP10-10"],
    price: 8,
    priceUnit: "USD",
    priceNote: "Custom sizes and coatings available",
    priceNoteZh: "可提供定制尺寸和镀膜",
    slug: "bk7-right-angle-prism-10mm"
  },
  {
    id: "prism-right-angle-bk7-lorp25.4-25.4",
    name: "BK7 Right Angle Prism LORP25.4-25.4",
    nameZh: "K9等边直角棱镜 LORP25.4-25.4",
    category: "optical-prisms",
    categoryZh: "光学棱镜",
    description: "High-quality BK7 right angle prism with 25.4mm leg length. 1 inch standard format. Ideal for beam deflection (90°), image erection, and beam steering applications. Features total internal reflection at the hypotenuse face. Precision manufactured with λ/4 surface flatness.",
    image: "images/products/optical-prisms/right-angle-prism.jpg",
    parameters: {
      material: "BK7",
      legLength: "25.4mm (1 inch)",
      angleTolerance: "±10 arcsec",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Custom (AR coating available)"
    },
    partNumbers: ["LORP25.4-25.4"],
    price: 15,
    priceUnit: "USD",
    priceNote: "Custom sizes and coatings available",
    priceNoteZh: "可提供定制尺寸和镀膜",
    slug: "bk7-right-angle-prism-25.4mm"
  },
  {
    id: "prism-uv-fused-silica-right-angle-lorpf25.4-25.4",
    name: "UV Fused Silica Right Angle Prism LORPF25.4-25.4",
    nameZh: "石英等边直径棱镜 LORPF25.4-25.4",
    category: "optical-prisms",
    categoryZh: "光学棱镜",
    description: "UV Fused Silica right angle prism with 25.4mm leg length. Excellent UV transmission (185-2100nm). Ideal for UV laser applications, beam steering, and spectroscopy. Features λ/4 surface flatness and ±10 arcsec angle tolerance.",
    image: "images/products/optical-prisms/fused-silica-right-angle-prism.jpg",
    parameters: {
      material: "UV Fused Silica",
      legLength: "25.4mm (1 inch)",
      wavelengthRange: "185-2100nm",
      angleTolerance: "±10 arcsec",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Custom"
    },
    partNumbers: ["LORPF25.4-25.4"],
    price: 22,
    priceUnit: "USD",
    priceNote: "UV applications preferred",
    priceNoteZh: "适用于紫外应用",
    slug: "uv-fused-silica-right-angle-prism-25.4mm"
  },
  {
    id: "prism-penta-lopr10-10",
    name: "Penta Prism LOPR10-10",
    nameZh: "五角棱镜 LOPR10-10",
    category: "optical-prisms",
    categoryZh: "光学棱镜",
    description: "Precision penta prism that deflects light by exactly 90° regardless of input angle. 10mm size with no image rotation or mirror reversal. Perfect for camera viewfinders, surveying instruments, and optical alignment systems.",
    image: "images/products/optical-prisms/penta-prism.jpg",
    parameters: {
      material: "BK7",
      size: "10mm",
      beamDeviation: "90°",
      angleTolerance: "±10 arcsec",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Custom"
    },
    partNumbers: ["LOPR10-10"],
    price: 25,
    priceUnit: "USD",
    priceNote: "Silver coating available for enhanced reflection",
    priceNoteZh: "可提供镀银增强反射",
    slug: "penta-prism-10mm"
  },
  {
    id: "prism-penta-lopr25.4-25.4",
    name: "Penta Prism LOPR25.4-25.4",
    nameZh: "五角棱镜 LOPR25.4-25.4",
    category: "optical-prisms",
    categoryZh: "光学棱镜",
    description: "Precision penta prism that deflects light by exactly 90° regardless of input angle. 25.4mm (1 inch) size with no image rotation or mirror reversal. 1 inch standard format. Perfect for camera viewfinders, surveying instruments, and optical alignment systems.",
    image: "images/products/optical-prisms/penta-prism.jpg",
    parameters: {
      material: "BK7",
      size: "25.4mm (1 inch)",
      beamDeviation: "90°",
      angleTolerance: "±10 arcsec",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Custom"
    },
    partNumbers: ["LOPR25.4-25.4"],
    price: 38,
    priceUnit: "USD",
    priceNote: "Silver coating available for enhanced reflection",
    priceNoteZh: "可提供镀银增强反射",
    slug: "penta-prism-25.4mm"
  },
  {
    id: "prism-corner-cube-locp25.4",
    name: "Corner Cube Prism LOCP25.4",
    nameZh: "角锥棱镜 LOCP25.4",
    category: "optical-prisms",
    categoryZh: "光学棱镜",
    description: "High-performance corner cube prism (retroreflector) with 25.4mm diameter. Returns incident light precisely back toward its source regardless of entry angle. Essential for laser ranging, surveying, and optical path length applications.",
    image: "images/products/optical-prisms/corner-cube-prism.jpg",
    parameters: {
      material: "BK7",
      diameter: "25.4mm (1 inch)",
      reflectance: ">95%",
      beamDeviation: "<3 arcsec",
      surfaceQuality: "40-20",
      coating: "Custom (HR coating available)"
    },
    partNumbers: ["LOCP25.4"],
    price: 55,
    priceUnit: "USD",
    priceNote: "HR coating available for laser applications",
    priceNoteZh: "可提供激光用高反膜",
    slug: "corner-cube-prism-25.4mm"
  },
  {
    id: "prism-dispersing-loep03",
    name: "Equilateral Dispersing Prism LOEP03",
    nameZh: "等边色散棱镜 LOEP03",
    category: "optical-prisms",
    categoryZh: "光学棱镜",
    description: "60° equilateral dispersing prism with 25.4mm sides for spectral analysis applications. Separates white light into its component wavelengths. Maximum dispersion with minimum reflection loss. Ideal for spectroscopy and wavelength separation.",
    image: "images/products/optical-prisms/dispersing-prism.jpg",
    parameters: {
      material: "BK7",
      apexAngle: "60°",
      sideLength: "25.4mm",
      angleTolerance: "±10 arcsec",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Custom (AR coating recommended)"
    },
    partNumbers: ["LOEP03"],
    price: 28,
    priceUnit: "USD",
    priceNote: "AR coating recommended for minimum loss",
    priceNoteZh: "建议镀增透膜减少损耗",
    slug: "dispersing-prism-25.4mm"
  },
  {
    id: "prism-roof-lorp03",
    name: "Roof Prism LORP03",
    nameZh: "屋脊棱镜 LORP03",
    category: "optical-prisms",
    categoryZh: "光学棱镜",
    description: "Compact roof prism with 40mm size. Combines two reflecting faces at 90° (roof) to maintain straight optical axis. Ideal for compact binoculars and imaging systems requiring inline configuration.",
    image: "images/products/optical-prisms/roof-prism.jpg",
    parameters: {
      material: "BK7",
      size: "40mm",
      roofAngle: "90°",
      angleTolerance: "±1 arcmin",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Custom"
    },
    partNumbers: ["LORP03"],
    price: 65,
    priceUnit: "USD",
    priceNote: "Silver coating available",
    priceNoteZh: "可提供镀银版本",
    slug: "roof-prism-40mm"
  },

  // =====================================================
  // OPTICAL FILTERS
  // =====================================================
  {
    id: "filter-narrowband-355nm",
    name: "Narrow Band Interference Filter 355nm",
    nameZh: "窄带干涉滤光片 355nm",
    category: "optical-filters",
    categoryZh: "光学滤光片",
    description: "Precision narrow band interference filter with center wavelength at 355nm UV. Features 10nm FWHM bandwidth and >63% peak transmission. 25.4mm diameter format. Ideal for UV laser line filtering, fluorescence microscopy, and spectral analysis.",
    image: "images/products/optical-filters/narrowband-filter.jpg",
    parameters: {
      type: "Narrow Band Interference",
      centerWavelength: "355nm",
      fwhm: "10nm",
      peakTransmission: ">63%",
      diameter: "25.4mm",
      wavelengthTolerance: "±0.2nm",
      surfaceQuality: "40-20",
      coating: "Multi-layer dielectric"
    },
    partNumbers: ["LONF355-25.4"],
    price: 85,
    priceUnit: "USD",
    priceNote: "Custom wavelengths available",
    priceNoteZh: "可提供定制波长",
    slug: "narrowband-filter-355nm"
  },
  {
    id: "filter-narrowband-532nm",
    name: "Narrow Band Interference Filter 532nm",
    nameZh: "窄带干涉滤光片 532nm",
    category: "optical-filters",
    categoryZh: "光学滤光片",
    description: "Precision narrow band interference filter with center wavelength at 532nm green. Features 10nm FWHM bandwidth and >50% peak transmission. 25.4mm diameter format. Ideal for green laser line filtering, fluorescence microscopy, and spectral analysis.",
    image: "images/products/optical-filters/narrowband-filter.jpg",
    parameters: {
      type: "Narrow Band Interference",
      centerWavelength: "532nm",
      fwhm: "10nm",
      peakTransmission: ">50%",
      diameter: "25.4mm",
      wavelengthTolerance: "±0.2nm",
      surfaceQuality: "40-20",
      coating: "Multi-layer dielectric"
    },
    partNumbers: ["LONF532-25.4"],
    price: 85,
    priceUnit: "USD",
    priceNote: "Custom wavelengths available",
    priceNoteZh: "可提供定制波长",
    slug: "narrowband-filter-532nm"
  },
  {
    id: "filter-narrowband-1064nm",
    name: "Narrow Band Interference Filter 1064nm",
    nameZh: "窄带干涉滤光片 1064nm",
    category: "optical-filters",
    categoryZh: "光学滤光片",
    description: "Precision narrow band interference filter with center wavelength at 1064nm infrared. Features 10nm FWHM bandwidth and >50% peak transmission. 25.4mm diameter format. Ideal for Nd:YAG laser filtering and IR spectroscopy applications.",
    image: "images/products/optical-filters/narrowband-filter.jpg",
    parameters: {
      type: "Narrow Band Interference",
      centerWavelength: "1064nm",
      fwhm: "10nm",
      peakTransmission: ">50%",
      diameter: "25.4mm",
      wavelengthTolerance: "±0.2nm",
      surfaceQuality: "40-20",
      coating: "Multi-layer dielectric"
    },
    partNumbers: ["LONF1064-25.4"],
    price: 85,
    priceUnit: "USD",
    priceNote: "Custom wavelengths available",
    priceNoteZh: "可提供定制波长",
    slug: "narrowband-filter-1064nm"
  },
  {
    id: "filter-neutral-density-od1",
    name: "Neutral Density Filter OD1.0",
    nameZh: "中性密度滤光片 OD1.0",
    category: "optical-filters",
    categoryZh: "光学滤光片",
    description: "Fixed neutral density filter with OD1.0 optical density (10% transmission). Provides uniform attenuation across visible spectrum. 25.4mm diameter size. Essential for laser power adjustment, imaging exposure control, and photometric applications.",
    image: "images/products/optical-filters/neutral-density-filter.jpg",
    parameters: {
      type: "Neutral Density",
      opticalDensity: "OD1.0",
      transmission: "10%",
      size: "25.4mm",
      wavelengthRange: "400-700nm (VIS)",
      odTolerance: "±1%",
      surfaceQuality: "40-20",
      substrate: "BK7 or Fused Silica"
    },
    partNumbers: ["LOFNF1-25.4"],
    price: 35,
    priceUnit: "USD",
    priceNote: "Other OD values available",
    priceNoteZh: "可提供其他OD值",
    slug: "neutral-density-filter-od1"
  },
  {
    id: "filter-neutral-density-od2",
    name: "Neutral Density Filter OD2.0",
    nameZh: "中性密度滤光片 OD2.0",
    category: "optical-filters",
    categoryZh: "光学滤光片",
    description: "Fixed neutral density filter with OD2.0 optical density (1% transmission). Higher optical density for greater light attenuation. 25.4mm diameter size. Essential for laser power adjustment and high-power photometric applications.",
    image: "images/products/optical-filters/neutral-density-filter.jpg",
    parameters: {
      type: "Neutral Density",
      opticalDensity: "OD2.0",
      transmission: "1%",
      size: "25.4mm",
      wavelengthRange: "400-700nm (VIS)",
      odTolerance: "±1%",
      surfaceQuality: "40-20",
      substrate: "BK7 or Fused Silica"
    },
    partNumbers: ["LOFNF2-25.4"],
    price: 35,
    priceUnit: "USD",
    priceNote: "Other OD values available",
    priceNoteZh: "可提供其他OD值",
    slug: "neutral-density-filter-od2"
  },
  {
    id: "filter-neutral-density-od3",
    name: "Neutral Density Filter OD3.0",
    nameZh: "中性密度滤光片 OD3.0",
    category: "optical-filters",
    categoryZh: "光学滤光片",
    description: "Fixed neutral density filter with OD3.0 optical density (0.1% transmission). Maximum optical density for extreme light attenuation. 25.4mm diameter size. Essential for precision laser power control and scientific photometric applications.",
    image: "images/products/optical-filters/neutral-density-filter.jpg",
    parameters: {
      type: "Neutral Density",
      opticalDensity: "OD3.0",
      transmission: "0.1%",
      size: "25.4mm",
      wavelengthRange: "400-700nm (VIS)",
      odTolerance: "±1%",
      surfaceQuality: "40-20",
      substrate: "BK7 or Fused Silica"
    },
    partNumbers: ["LOFNF3-25.4"],
    price: 48,
    priceUnit: "USD",
    priceNote: "Other OD values available",
    priceNoteZh: "可提供其他OD值",
    slug: "neutral-density-filter-od3"
  },

  // =====================================================
  // OPTICAL BEAMSPLITTERS
  // =====================================================
  {
    id: "beamsplitter-plate-lobp25.4-450-650",
    name: "Beamsplitter Plate LOBP25.4-450/650",
    nameZh: "分光平片 LOBP25.4-450/650",
    category: "optical-beamsplitters",
    categoryZh: "光学分光片",
    description: "Precision beamsplitter plate with 50:50 split ratio over 450-650nm visible range. 25.4mm (1 inch) diameter format. Dielectric coating on hypotenuse face with AR coating on entrance/exit faces. Perfect for interferometry, beam sampling, and optical monitoring.",
    image: "images/products/optical-beamsplitters/beamsplitter-plate.jpg",
    parameters: {
      type: "Beamsplitter Plate",
      size: "Φ25.4mm",
      thickness: "3mm",
      wavelengthRange: "450-650nm",
      splitRatio: "50:50 (±2%)",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      parallelism: "<1 arcmin"
    },
    partNumbers: ["LOBP25.4-450/650"],
    price: 68,
    priceUnit: "USD",
    priceNote: "Custom split ratios available",
    priceNoteZh: "可提供定制分光比",
    slug: "beamsplitter-plate-450-650nm"
  },
  {
    id: "beamsplitter-cube-locbs12.7-532",
    name: "Cube Beamsplitter LOCBS12.7-532",
    nameZh: "立方体分光镜 LOCBS12.7-532",
    category: "optical-beamsplitters",
    categoryZh: "光学分光片",
    description: "High-quality cube beamsplitter optimized for 532nm green wavelength. 12.7mm (1/2 inch) cube size with 50:50 split ratio. Multi-layer dielectric coating with minimal absorption. No beam deviation or ghosting. Ideal for laser systems and interferometry.",
    image: "images/products/optical-beamsplitters/cube-beamsplitter.jpg",
    parameters: {
      type: "Cube Beamsplitter",
      size: "12.7mm (1/2 inch)",
      wavelength: "532nm",
      splitRatio: "50:50 (±2%)",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      parallelism: "<1 arcmin",
      material: "BK7 prisms"
    },
    partNumbers: ["LOCBS12.7-532"],
    price: 48,
    priceUnit: "USD",
    priceNote: "Non-polarizing and polarizing versions available",
    priceNoteZh: "可提供消偏振和偏振版本",
    slug: "cube-beamsplitter-12.7mm-532nm"
  },
  {
    id: "beamsplitter-cube-locbs25.4-532",
    name: "Cube Beamsplitter LOCBS25.4-532",
    nameZh: "立方体分光镜 LOCBS25.4-532",
    category: "optical-beamsplitters",
    categoryZh: "光学分光片",
    description: "High-quality cube beamsplitter optimized for 532nm green wavelength. 25.4mm (1 inch) cube size with 50:50 split ratio. Multi-layer dielectric coating with minimal absorption. No beam deviation or ghosting. 1 inch format for standard optical mounts.",
    image: "images/products/optical-beamsplitters/cube-beamsplitter.jpg",
    parameters: {
      type: "Cube Beamsplitter",
      size: "25.4mm (1 inch)",
      wavelength: "532nm",
      splitRatio: "50:50 (±2%)",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      parallelism: "<1 arcmin",
      material: "BK7 prisms"
    },
    partNumbers: ["LOCBS25.4-532"],
    price: 75,
    priceUnit: "USD",
    priceNote: "Non-polarizing and polarizing versions available",
    priceNoteZh: "可提供消偏振和偏振版本",
    slug: "cube-beamsplitter-25.4mm-532nm"
  },
  {
    id: "beamsplitter-cube-locbs25.4-1064",
    name: "Cube Beamsplitter LOCBS25.4-1064",
    nameZh: "立方体分光镜 LOCBS25.4-1064",
    category: "optical-beamsplitters",
    categoryZh: "光学分光片",
    description: "High-quality cube beamsplitter optimized for 1064nm Nd:YAG laser wavelength. 25.4mm (1 inch) cube size with 50:50 split ratio. Multi-layer dielectric coating with minimal absorption. No beam deviation or ghosting. Ideal for laser systems and interferometry.",
    image: "images/products/optical-beamsplitters/cube-beamsplitter.jpg",
    parameters: {
      type: "Cube Beamsplitter",
      size: "25.4mm (1 inch)",
      wavelength: "1064nm",
      splitRatio: "50:50 (±2%)",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      parallelism: "<1 arcmin",
      material: "BK7 prisms"
    },
    partNumbers: ["LOCBS25.4-1064"],
    price: 75,
    priceUnit: "USD",
    priceNote: "Non-polarizing and polarizing versions available",
    priceNoteZh: "可提供消偏振和偏振版本",
    slug: "cube-beamsplitter-25.4mm-1064nm"
  },
  {
    id: "beamsplitter-non-polarizing-lonpbs25.4-532",
    name: "Non-Polarizing Cube Beamsplitter LONPBS25.4-532",
    nameZh: "消偏振立方体分光棱镜 LONPBS25.4-532",
    category: "optical-beamsplitters",
    categoryZh: "光学分光片",
    description: "Non-polarizing cube beamsplitter with wavelength-independent 50:50 split ratio. 25.4mm (1 inch) size optimized for 532nm. Maintains equal split regardless of polarization state. Perfect for white light applications and polarization-insensitive systems.",
    image: "images/products/optical-beamsplitters/non-polarizing-cube-beamsplitter.jpg",
    parameters: {
      type: "Non-Polarizing Cube Beamsplitter",
      size: "25.4mm (1 inch)",
      wavelength: "532nm",
      splitRatio: "50:50 (±5%)",
      transmission: "50±5%",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm",
      coating: "Non-polarizing dielectric"
    },
    partNumbers: ["LONPBS25.4-532"],
    price: 145,
    priceUnit: "USD",
    priceNote: "Custom wavelengths available",
    priceNoteZh: "可提供定制波长",
    slug: "non-polarizing-cube-25.4mm-532nm"
  },
  {
    id: "beamsplitter-polarizing-lopbs25.4-532",
    name: "Polarizing Cube Beamsplitter LOPBS25.4-532",
    nameZh: "偏振立方体分光棱镜 LOPBS25.4-532",
    category: "optical-beamsplitters",
    categoryZh: "光学分光片",
    description: "High-performance polarizing cube beamsplitter for 532nm. 25.4mm (1 inch) cube. Transmits P-polarization (>95%) while reflecting S-polarization (>99%). Extinction ratio >500:1. Essential for laser polarization optics and interferometry.",
    image: "images/products/optical-beamsplitters/polarizing-cube-beamsplitter.jpg",
    parameters: {
      type: "Polarizing Cube Beamsplitter",
      size: "25.4mm (1 inch)",
      wavelength: "532nm",
      Tp: ">95%",
      Ts: "<1%",
      Rs: ">99%",
      extinctionRatio: ">500:1",
      surfaceQuality: "40-20",
      surfaceFlatness: "λ/4@632.8nm"
    },
    partNumbers: ["LOPBS25.4-532"],
    price: 195,
    priceUnit: "USD",
    priceNote: "Custom wavelengths available",
    priceNoteZh: "可提供定制波长",
    slug: "polarizing-cube-25.4mm-532nm"
  },

  // =====================================================
  // OPTICAL WAVEPLATES
  // =====================================================
  {
    id: "waveplate-multiple-order-quarter-532",
    name: "Multiple Order Quarter Waveplate 532nm",
    nameZh: "多级四分之一波片 532nm",
    category: "optical-waveplates",
    categoryZh: "光学波片",
    description: "Multiple order quarter waveplate with λ/4 phase retardation at 532nm. 12.7mm (1/2 inch) diameter quartz crystal. Features λ/100 phase delay accuracy and high damage threshold. Cost-effective solution for laser polarization control.",
    image: "images/products/optical-waveplates/multiple-order-waveplate.jpg",
    parameters: {
      type: "Multiple Order Waveplate",
      phase: "λ/4 (Quarter Wave)",
      wavelength: "532nm",
      diameter: "12.7mm (1/2 inch)",
      phaseAccuracy: "λ/100",
      surfaceQuality: "20-10",
      wavefrontAberration: "λ/8@632.8nm",
      coating: "AR coated both surfaces"
    },
    partNumbers: ["LOWPM-12.7Q-532"],
    price: 35,
    priceUnit: "USD",
    priceNote: "Custom wavelengths available",
    priceNoteZh: "可提供定制波长",
    slug: "multiple-order-quarter-waveplate-12.7mm-532nm"
  },
  {
    id: "waveplate-multiple-order-half-1064",
    name: "Multiple Order Half Waveplate 1064nm",
    nameZh: "多级二分之一波片 1064nm",
    category: "optical-waveplates",
    categoryZh: "光学波片",
    description: "Multiple order half waveplate with λ/2 phase retardation at 1064nm. 25.4mm (1 inch) diameter quartz crystal. Features λ/100 phase delay accuracy. Cost-effective solution for laser polarization rotation and control in Nd:YAG laser systems.",
    image: "images/products/optical-waveplates/multiple-order-waveplate.jpg",
    parameters: {
      type: "Multiple Order Waveplate",
      phase: "λ/2 (Half Wave)",
      wavelength: "1064nm",
      diameter: "25.4mm (1 inch)",
      phaseAccuracy: "λ/100",
      surfaceQuality: "20-10",
      wavefrontAberration: "λ/8@632.8nm",
      coating: "AR coated both surfaces"
    },
    partNumbers: ["LOWPM-25.4H-1064"],
    price: 65,
    priceUnit: "USD",
    priceNote: "Custom wavelengths available",
    priceNoteZh: "可提供定制波长",
    slug: "multiple-order-half-waveplate-25.4mm-1064nm"
  },
  {
    id: "waveplate-zero-order-cemented-quarter-532",
    name: "Cemented Zero Order Quarter Waveplate 532nm",
    nameZh: "胶合零级四分之一波片 532nm",
    category: "optical-waveplates",
    categoryZh: "光学波片",
    description: "Cemented zero order quarter waveplate with λ/4 phase retardation at 532nm. 25.4mm (1 inch) diameter. Zero order design provides excellent temperature stability and broad wavelength acceptance. Ideal for precision polarization control in laser systems.",
    image: "images/products/optical-waveplates/cemented-zero-order-waveplate.jpg",
    parameters: {
      type: "Cemented Zero Order Waveplate",
      phase: "λ/4 (Quarter Wave)",
      wavelength: "532nm",
      diameter: "25.4mm (1 inch)",
      phaseAccuracy: "λ/100",
      surfaceQuality: "20-10",
      wavefrontAberration: "λ/8@632.8nm",
      temperatureStability: "Excellent",
      coating: "AR coated both surfaces"
    },
    partNumbers: ["LOWPCZ-25.4Q-532"],
    price: 98,
    priceUnit: "USD",
    priceNote: "Air-spaced version available for high power",
    priceNoteZh: "可提供空气隙版本用于高功率",
    slug: "cemented-zero-order-quarter-waveplate-25.4mm-532nm"
  },
  {
    id: "waveplate-zero-order-cemented-half-1064",
    name: "Cemented Zero Order Half Waveplate 1064nm",
    nameZh: "胶合零级二分之一波片 1064nm",
    category: "optical-waveplates",
    categoryZh: "光学波片",
    description: "Cemented zero order half waveplate with λ/2 phase retardation at 1064nm. 25.4mm (1 inch) diameter. Zero order design provides excellent temperature stability and broad wavelength acceptance. Ideal for precision polarization rotation in Nd:YAG laser systems.",
    image: "images/products/optical-waveplates/cemented-zero-order-waveplate.jpg",
    parameters: {
      type: "Cemented Zero Order Waveplate",
      phase: "λ/2 (Half Wave)",
      wavelength: "1064nm",
      diameter: "25.4mm (1 inch)",
      phaseAccuracy: "λ/100",
      surfaceQuality: "20-10",
      wavefrontAberration: "λ/8@632.8nm",
      temperatureStability: "Excellent",
      coating: "AR coated both surfaces"
    },
    partNumbers: ["LOWPCZ-25.4H-1064"],
    price: 98,
    priceUnit: "USD",
    priceNote: "Air-spaced version available for high power",
    priceNoteZh: "可提供空气隙版本用于高功率",
    slug: "cemented-zero-order-half-waveplate-25.4mm-1064nm"
  },
  {
    id: "waveplate-air-spaced-quarter-1064",
    name: "Air Spaced Zero Order Quarter Waveplate 1064nm",
    nameZh: "空气隙零级四分之一波片 1064nm",
    category: "optical-waveplates",
    categoryZh: "光学波片",
    description: "Air spaced zero order quarter waveplate with λ/4 phase retardation at 1064nm. 25.4mm (1 inch) diameter. Air gap design enables high power handling >99% transmission. Essential for high-power laser polarization control applications.",
    image: "images/products/optical-waveplates/air-spaced-waveplate.jpg",
    parameters: {
      type: "Air Spaced Zero Order Waveplate",
      phase: "λ/4 (Quarter Wave)",
      wavelength: "1064nm",
      diameter: "25.4mm (1 inch)",
      phaseAccuracy: "λ/100",
      surfaceQuality: "20-10",
      transmission: ">99%",
      powerHandling: "High power",
      coating: "AR coated both surfaces"
    },
    partNumbers: ["LOWPAZ-25.4Q-1064"],
    price: 135,
    priceUnit: "USD",
    priceNote: "Optimized for high power laser applications",
    priceNoteZh: "专为高功率激光应用优化",
    slug: "air-spaced-quarter-waveplate-25.4mm-1064nm"
  },
  {
    id: "waveplate-dual-wavelength",
    name: "Dual Wavelength Waveplate 1064+532nm",
    nameZh: "双波长波片 1064+532nm",
    category: "optical-waveplates",
    categoryZh: "光学波片",
    description: "Dual wavelength waveplate for simultaneous control at 1064nm and 532nm. 25.4mm (1 inch) diameter. λ/2@1064nm + λ@532nm retardation combination. Ideal for Nd:YAG harmonic separation and polarization conversion systems.",
    image: "images/products/optical-waveplates/dual-wavelength-waveplate.jpg",
    parameters: {
      type: "Dual Wavelength Waveplate",
      wavelengthCombination: "1064nm + 532nm",
      retardation: "λ/2@1064nm + λ@532nm",
      diameter: "25.4mm (1 inch)",
      phaseAccuracy: "λ/100",
      surfaceQuality: "20-10",
      wavefrontAberration: "λ/8@632.8nm",
      coating: "AR coated both surfaces"
    },
    partNumbers: ["LOWPDW25.4-1"],
    price: 125,
    priceUnit: "USD",
    priceNote: "Custom wavelength combinations available",
    priceNoteZh: "可提供定制波长组合",
    slug: "dual-wavelength-waveplate-25.4mm"
  },

  // =====================================================
  // OPTICAL POLARIZERS
  // =====================================================
  {
    id: "polarizer-linear-vis-lolo25.4",
    name: "Visible Linear Polarizer 25.4mm",
    nameZh: "可见光线偏振片 25.4mm",
    category: "optical-polarizers",
    categoryZh: "光学偏振片",
    description: "High-quality thin-film linear polarizer for visible spectrum (400-700nm). 25.4mm (1 inch) diameter. Features >50% transmission with high extinction ratio. Film polarizers also serve as neutral density attenuators.",
    image: "images/products/optical-polarizers/linear-polarizer.jpg",
    parameters: {
      type: "Thin-Film Linear Polarizer",
      diameter: "25.4mm (1 inch)",
      wavelengthRange: "400-700nm",
      transmission: ">50%",
      extinctionRatio: ">1000:1",
      surfaceQuality: "60-40",
      clearAperture: ">90%"
    },
    partNumbers: ["LOLO25.4"],
    price: 42,
    priceUnit: "USD",
    priceNote: "Custom sizes available",
    priceNoteZh: "可提供定制尺寸",
    slug: "linear-polarizer-25.4mm"
  },
  {
    id: "polarizer-ir-loirp-750-1150",
    name: "IR Polarizer LOIRP-750/1150",
    nameZh: "红外偏振片 LOIRP-750/1150",
    category: "optical-polarizers",
    categoryZh: "光学偏振片",
    description: "Wideband infrared polarizer covering 750-1150nm range. 25.4mm (1 inch) diameter format. Features high transmission (>87-93%) and excellent extinction ratio (>1000:1). Ideal for IR imaging, spectroscopy, and laser polarization control in near-IR applications.",
    image: "images/products/optical-polarizers/ir-polarizer.jpg",
    parameters: {
      type: "IR Polarizer",
      diameter: "25.4mm (1 inch)",
      wavelengthRange: "750-1150nm",
      transmission: ">87-93%",
      extinctionRatio: ">1000:1",
      surfaceQuality: "60-40",
      clearAperture: ">90%"
    },
    partNumbers: ["LOIRP-750/1150"],
    price: 85,
    priceUnit: "USD",
    priceNote: "Custom wavelengths available",
    priceNoteZh: "可提供定制波长",
    slug: "ir-polarizer-750-1150nm"
  },
  {
    id: "polarizer-glan-taylor-logtpc-10-350-2300",
    name: "Glan Taylor Prism LOGTPC-10-350/2300",
    nameZh: "格兰泰勒棱镜 LOGTPC-10-350/2300",
    category: "optical-polarizers",
    categoryZh: "光学偏振片",
    description: "High-performance Glan Taylor prism polarizer made from natural calcite crystal. 10mm clear aperture covering 350-2300nm (UV to near-IR). Features extinction ratio 10⁻⁵, air-spaced design for no adhesive absorption. Damage threshold >100MW/cm². Complete with black anodized aluminum mount.",
    image: "images/products/optical-polarizers/glan-taylor-prism.jpg",
    parameters: {
      type: "Glan Taylor Prism",
      material: "Calcite",
      aperture: "10mm",
      wavelengthRange: "350-2300nm",
      extinctionRatio: "10⁻⁵",
      damageThreshold: ">100MW/cm²",
      surfaceQuality: "20-10",
      acceptanceAngle: ">7.7°",
      mount: "Black anodized aluminum"
    },
    partNumbers: ["LOGTPC-10-350/2300"],
    price: 185,
    priceUnit: "USD",
    priceNote: "α-BBO version for UV available",
    priceNoteZh: "可提供α-BBO紫外版本",
    slug: "glan-taylor-prism-10mm"
  },
  {
    id: "polarizer-glan-taylor-logtpc-12.7-350-2300",
    name: "Glan Taylor Prism LOGTPC-12.7-350/2300",
    nameZh: "格兰泰勒棱镜 LOGTPC-12.7-350/2300",
    category: "optical-polarizers",
    categoryZh: "光学偏振片",
    description: "High-performance Glan Taylor prism polarizer made from natural calcite crystal. 12.7mm (1/2 inch) clear aperture covering 350-2300nm (UV to near-IR). Features extinction ratio 10⁻⁵, air-spaced design for no adhesive absorption. Damage threshold >100MW/cm². Complete with black anodized aluminum mount.",
    image: "images/products/optical-polarizers/glan-taylor-prism.jpg",
    parameters: {
      type: "Glan Taylor Prism",
      material: "Calcite",
      aperture: "12.7mm (1/2 inch)",
      wavelengthRange: "350-2300nm",
      extinctionRatio: "10⁻⁵",
      damageThreshold: ">100MW/cm²",
      surfaceQuality: "20-10",
      acceptanceAngle: ">7.7°",
      mount: "Black anodized aluminum"
    },
    partNumbers: ["LOGTPC-12.7-350/2300"],
    price: 265,
    priceUnit: "USD",
    priceNote: "α-BBO version for UV available",
    priceNoteZh: "可提供α-BBO紫外版本",
    slug: "glan-taylor-prism-12.7mm"
  },
  {
    id: "polarizer-glan-laser-loglpc-10",
    name: "Glan Laser Prism LOGLPC-10",
    nameZh: "格兰激光棱镜 LOGLPC-10",
    category: "optical-polarizers",
    categoryZh: "光学偏振片",
    description: "High-power Glan Laser prism polarizer for strong laser systems. 10mm aperture, 350-2300nm range. Features extremely high damage threshold >500MW/cm² with escape window design. Air-spaced calcite construction. Essential for high-power laser polarization control.",
    image: "images/products/optical-polarizers/glan-laser-prism.jpg",
    parameters: {
      type: "Glan Laser Prism",
      material: "Calcite",
      aperture: "10mm",
      wavelengthRange: "350-2300nm",
      extinctionRatio: "10⁻⁵",
      damageThreshold: ">500MW/cm²",
      surfaceQuality: "20-10",
      acceptanceAngle: ">7.7°",
      mount: "Black anodized aluminum"
    },
    partNumbers: ["LOGLPC-10"],
    price: 225,
    priceUnit: "USD",
    priceNote: "For high power laser applications",
    priceNoteZh: "适用于高功率激光应用",
    slug: "glan-laser-prism-10mm"
  },
  {
    id: "polarizer-glan-laser-loglpc-12.7",
    name: "Glan Laser Prism LOGLPC-12.7",
    nameZh: "格兰激光棱镜 LOGLPC-12.7",
    category: "optical-polarizers",
    categoryZh: "光学偏振片",
    description: "High-power Glan Laser prism polarizer for strong laser systems. 12.7mm (1/2 inch) aperture, 350-2300nm range. Features extremely high damage threshold >500MW/cm² with escape window design. Air-spaced calcite construction. Essential for high-power laser polarization control.",
    image: "images/products/optical-polarizers/glan-laser-prism.jpg",
    parameters: {
      type: "Glan Laser Prism",
      material: "Calcite",
      aperture: "12.7mm (1/2 inch)",
      wavelengthRange: "350-2300nm",
      extinctionRatio: "10⁻⁵",
      damageThreshold: ">500MW/cm²",
      surfaceQuality: "20-10",
      acceptanceAngle: ">7.7°",
      mount: "Black anodized aluminum"
    },
    partNumbers: ["LOGLPC-12.7"],
    price: 325,
    priceUnit: "USD",
    priceNote: "For high power laser applications",
    priceNoteZh: "适用于高功率激光应用",
    slug: "glan-laser-prism-12.7mm"
  },
  {
    id: "polarizer-wollaston-lowpc-10",
    name: "Wollaston Prism LOWPC-10",
    nameZh: "渥拉斯通棱镜 LOWPC-10",
    category: "optical-polarizers",
    categoryZh: "光学偏振片",
    description: "Wollaston prism that separates unpolarized light into two orthogonal linearly polarized beams with 19° beam deviation. 10mm aperture covering 350-2300nm. Made from calcite crystal with MgF2 coating. Ideal for polarimetry and beam separation applications.",
    image: "images/products/optical-polarizers/wollaston-prism.jpg",
    parameters: {
      type: "Wollaston Prism",
      material: "Calcite",
      aperture: "10mm",
      wavelengthRange: "350-2300nm",
      beamDeviation: "19°",
      extinctionRatio: "10⁻⁵",
      damageThreshold: ">500MW/cm²",
      surfaceQuality: "20-10",
      mount: "Black anodized aluminum"
    },
    partNumbers: ["LOWPC-10"],
    price: 165,
    priceUnit: "USD",
    priceNote: "Custom beam deviation available",
    priceNoteZh: "可提供定制分离角",
    slug: "wollaston-prism-10mm"
  }
];

// Export for use in ES modules
if (typeof module !== 'undefined' && module.exports) {
  module.exports = PRODUCTS;
}
